# encoding: UTF-8
require "json"
require "date"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "data")
DATE = "2026-09-07"
GENERATED_AT = "2026-09-07T04:00:00+08:00"
NOW = DateTime.parse(GENERATED_AT)

def art(id:, key:, name:, tier:, country:, cities:, media:, work:, comment:, url:, image:)
  {"category"=>"作品/展覽","status"=>"官方來源","updated"=>DATE,"id"=>id,"dedupeKey"=>key,"name"=>name,"tier"=>tier,"region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>work,"classicImage"=>image,"classicDesc"=>comment,"relatedByCity"=>[]}
end

koer = "https://www.koer.or.at"
arts_data = [
  ["current","koer-roadside-picnic","Michèle Pagel｜路邊野餐","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Ljuba-Welitsch-Promenade"],["公共雕塑","地景裝置","參與式藝術"],"Picknick am Wegesrand｜2026","放大的三明治包裝、橘子、拖鞋與棋后被鑄成柔色混凝土，像外星訪客留下的野餐遺物；作品把住宅庭院變成可坐、可玩，也能思考消費與城市記憶的異尺度地景。","#{koer}/projects/picknick-am-wegesrand/","#{koer}/site/assets/files/15364/kro5619.500x0.jpg"],
  ["current","koer-pfingstspiel","Florentina Holzinger｜聖靈降臨劇","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Vienna Skating Club","Lothringer Straße"],["行為藝術","機械裝置","公共展演"],"Pfingstspiel｜2026","以『身體與機器的神劇』測試公共空間能容納的特技、機械與集體儀式，並把威尼斯雙年展奧地利館對水、宗教與淨化的提問帶回維也納。","#{koer}/projects/pfingstspiel/","#{koer}/site/assets/files/14694/holzinger_pfingstspiel_prolog_c_koer_img_1523.500x0.jpeg"],
  ["current","koer-dohnal-ar","Tricky Women Tricky Realities｜先驅者的痕跡","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Johanna-Dohnal-Platz"],["擴增實境","女性主義藝術","數位紀念地景"],"Remembering a Pioneer in AR｜2025","六位藝術家以擴增實境動畫回應 Johanna Dohnal 的女性權利改革，讓廣場上的紀念不再依靠單一雕像，而由手機、身體移動與當代社會議題共同啟動。","#{koer}/projects/spuren-einer-vordenkerin/","#{koer}/site/assets/files/14502/collage_susi_jirkuff-_quelle_walter_swistelnicki_johanna_dohnal_archiv.500x0.jpg"],
  ["current","koer-design-anonymous","Joanna Zabielska｜無名者的設計","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Brunnenmarkt","Yppenpark"],["社會參與","纖維藝術","市場表演"],"Design of the Anonymous｜2025","市場工作者與訪客把紅白藍編織袋縫成服裝、牆與空間，搭配收據詩、廣播、共食和週日表演，讓市場日常成為共同設計永續生活的公共工作室。","#{koer}/projects/das-design-des-anonymen/","#{koer}/site/assets/files/14030/01_c_sebastian_kraner.500x0.jpg"],
  ["current","koer-invisible-waters","藝術與時間攝影工作室｜看不見的水與隱藏路徑","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Getreidemarkt","Academy of Fine Arts Vienna"],["地景研究","攝影","城市步行"],"Invisible Waters and Hidden Paths｜2025–2026","學生與藝術家以每月展演、工作坊及城市步行研究維也納的水與自然，把美術學院周邊綠地持續改寫成開放式展場。","#{koer}/projects/unsichtbare-gewaesser-und-versteckte-wege/","#{koer}/site/assets/files/14118/franke_flora_inseln.500x0.jpg"],
  ["current","koer-lost-garden","Christian Kosmas Mayer｜失落的花園","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Meidling Station","Prónay Garden"],["玻璃壁畫","鐵路藝術","歷史地景"],"The Lost Garden｜2025","車站玻璃壁畫以檔案研究與生成影像追索被鐵路抹去的 Prónay 花園，不重建單一往昔，而讓通勤者辨認現代基礎設施如何同時帶來進步與地景消失。","#{koer}/projects/der-verlorene-garten/","#{koer}/site/assets/files/13855/dsc0210_kleiner.500x0.jpg"],
  ["current","koer-polit-mobile","Susi Rogenhofer｜藝術政治行動車","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Meidlinger Platzl"],["社會參與","影像裝置","公共論壇"],"Kunst-Polit-Mobil｜2024","以競選集會般的移動舞台、跨文化桌布、雙螢幕影像與工作坊拆解民粹、陰謀敘事和『人民』的想像，重新啟動廣場作為公共論辯場所。","#{koer}/projects/polit-mobil/","#{koer}/site/assets/files/13866/pxl_20240928_155131314.500x0.jpg"],
  ["current","koer-projection-guerrilla","starsky｜正常才瘋狂！我們比迷信更強大","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","MuseumsQuartier","Heldenplatz","Burgtheater"],["文字投影","行動藝術","光藝術"],"das normal ist irr!｜2024","投影游擊隊從博物館區移動到國會、總理府與城堡劇院，把平權、人權、女性主義文字短暫投上權力建築，使遊行、光與城市立面合成可移動的公共發聲裝置。","#{koer}/projects/das-normal-ist-irr-wir-sind-maechtiger-als-irrglaubt/","#{koer}/site/assets/files/12556/starsky_niemand_guerilla_osaka_423_2_1200.500x0.jpg"],
  ["current","koer-wirwasser","GELATIN｜我們的水","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Helmut-Zilk-Park","Sonnwendviertel"],["噴泉藝術","互動雕塑","水地景"],"WirWasser｜2023","一圈介於人物與生物之間的彩色形體共同托住水池，中央水柱每日以不同色光升起；作品讓巴洛克噴泉的歡樂與水資源責任成為可坐、可玩、可共同維護的地景。","#{koer}/projects/wirwasser/","#{koer}/site/assets/files/12402/kleiner_koer_wienerwasserbrunnen_-7400.500x0.jpg"],
  ["current","koer-open-street-gallery","SOON Art Studio 等｜露天街頭藝術藝廊","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Ottakring","Kendlerstraße"],["街頭藝術","壁畫","環境藝術"],"Open Street Art Gallery｜2023","八位藝術家把垃圾處理場約兩百平方公尺外牆變成策展式街頭藝廊，以不同圖像語言回應廢棄物、永續與城市環境教育。","#{koer}/projects/open-street-art-gallery/","#{koer}/site/assets/files/12333/photo_oct_08_2023-_9_59_29_pm.500x0.jpg"],

  ["classic-global","koer-sound-karaoke","Sophie Bösker、Ana Mumladze Detering、Fabian Ritzi｜卡拉 OK 之聲","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Maria-Trapp-Platz","Seestadt Aspern"],["參與式表演","聲音藝術","城市記憶"],"Sound of Karaoke｜2023","居民在 Maria-Trapp-Platz 共同重演《真善美》歌曲並交換遷徙故事，讓好萊塢塑造的奧地利神話與今日多文化城市經驗正面碰撞。","#{koer}/projects/sound-of-karaoke/","#{koer}/site/assets/files/12320/kleiner_pressebild_neu_c_sophie_boesker_2023.500x0.jpg"],
  ["classic-global","koer-water-mask-night","transparadiso｜水、面具、夜","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Penzing","Wien River"],["城市步行","地景表演","直接城市主義"],"Water, Mask, Night｜2023","三次以水系、城市替身與夜間霓虹為主題的步行和表演，讀取缺乏單一中心的 Penzing，並把藝術轉成長期介入都市規劃的研究工具。","#{koer}/projects/wasser-maske-nacht/","#{koer}/site/assets/files/12372/harry_glu_eck-shell-tankstelle_img_1521med_kleiner.500x0.jpg"],
  ["classic-global","koer-falsified-maps","Cosima Terrasse｜做過記號的地圖","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Viktor-Adler-Markt","Alsergrund"],["數位地圖","城市步行","資料藝術"],"Gezinkte Karten｜2023–2025","藝術家與資料科學家以 Street View、評分和評論引導觀眾走向城市最好與最差評地點，揭露演算法地圖如何被商業利益和評價經濟共同塑形。","#{koer}/projects/gezinkte-karten/","#{koer}/site/assets/files/12361/gezinkte_karten_videostill_c_cosima_terrasse_1.500x0.jpg"],
  ["classic-global","koer-how-to-disappear","Total Refusal｜如何消失","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Heldenplatz","Deserters Memorial"],["擴增實境","遊戲影像","反戰藝術"],"How to Disappear｜2021","作品在逃兵紀念地透過網頁擴增實境播放由電玩《戰地風雲 V》挪用而成的影片，把違反遊戲規則的逃離動作轉化為對戰爭、服從與抵抗的公共思考。","#{koer}/projects/how-to-disappear/","#{koer}/site/assets/files/12096/02_bytotalrefusal.500x0.jpg"],
  ["classic-global","koer-while-no-one-watching","Alex Deutinger、Alexander Gottfarb｜無人注視時","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Floridsdorf","Pius-Parsch-Platz"],["行為藝術","臨時建築","監控批判"],"While No One Is Watching｜2023","兩位表演者以防暴警察裝備住進由群眾管制欄搭成的六公尺監控塔，連續四天巡邏並與路人互動，反問軍事化警力究竟如何改變安全感與公共空間。","#{koer}/projects/while-no-one-is-watching/","#{koer}/site/assets/files/12111/kleiner_09_while_no_one_is_watching_nikola_milatovic_2020.500x0.jpg"],

  ["classic-german","museum-same-boat","Inges Idee｜同舟／國際水域","經典檔案庫","德國 / Parow-Stralsund",["Parow","Stralsund","施特拉爾松","Marinetechnikschule"],["場域雕塑","公共藝術","航海意象"],"Im selben Boot／In internationalen Gewässern｜2003","翻倒在草地上的藍色密閉船體介於大型玩具、沉船和異物之間，以幽默的尺度錯置回應海軍技術學校的制度、海洋與共同命運。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/im-selben-boot-in-internationalen-gewassern","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/e204810a76c60058d3acd9e758fa64df31c1517a.jpg"],
  ["classic-german","museum-famous-libraries","Candida Höfer｜著名圖書館","經典檔案庫","德國 / Frankfurt am Main",["Frankfurt am Main","法蘭克福","Deutsche Nationalbibliothek"],["攝影","建築整合","知識空間"],"Berühmte Bibliotheken｜1996","一組冷靜而精確的建築攝影把世界圖書館從修道院式封閉書庫帶到明亮公共閱覽室，並在德國國家圖書館形成關於知識儲存與空間制度的比較圖譜。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/beruhmte-bibliotheken","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/62ae1ca87f2aefb3ce1e137869ff5306fa8bd6f0.jpg"],
  ["classic-german","museum-red-underwing","Renate Anger｜紅帶蛾","經典檔案庫","德國 / Berlin",["Berlin","柏林","Bendlerblock","Stauffenbergsaal"],["攝影裝置","歷史空間","建築藝術"],"Ein Falter: Catocala nupta／Rotes Ordensband｜2002","八張蛾翅影像以詩性而非英雄雕像回應 Bendlerblock 的抵抗史；脆弱、偽裝與紅色閃現，使會議室成為可持續閱讀歷史的內部地景。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/ein-falter-catocala-nupta-rotes-ordensband","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/2997ea2679adb86b0126dc423842ea6f2e3a4aac.jpg"],
  ["classic-german","museum-grande-fenetre","Daniel Buren｜大窗","經典檔案庫","德國 / Berlin",["Berlin","柏林","Wilhelmstraße","BMAS"],["場域特定","色彩玻璃","建築整合"],"La Grande Fenêtre｜2001","Buren 以條紋、色彩與玻璃改寫聯邦勞工與社會部入口大廳的網格，讓新舊建築的連接處不只是通行空間，也成為觀看歷史權力建築的巨大框景。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/la-grande-fenetre","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/fc43379f8af4bea0f4b69fd6a4f02a808a710ea9.jpg"],
  ["classic-german","museum-all-over-structures","François Morellet｜遍佈結構","經典檔案庫","德國 / Hamburg",["Hamburg","漢堡","Helmut-Schmidt-Universität"],["幾何壁畫","建築整合","色彩系統"],"All-Over Strukturen｜1976","紅藍線條與十字形依幾何規則覆蓋八角形餐廳核心，隨行走產生密度與色彩主導的變化，是具體藝術把建築構造轉譯為完整視覺系統的經典案例。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/all-over-strukturen","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/623af61015074a8ff235f3de622a92a0fab9d195.jpg"]
]

arts = arts_data.each_with_index.map do |a, i|
  group,key,title,tier,country,cities,media,work,comment,url,image = a
  number = group == "current" ? i + 1 : group == "classic-global" ? i - 9 : i - 14
  art(id:"#{group}-#{DATE}-#{format('%02d', number)}",key:"art-#{DATE}-#{key}",name:"#{format('%02d', number)}｜#{title}",tier:tier,country:country,cities:cities,media:media,work:work,comment:comment,url:url,image:image)
end

def call(n:, key:, name:, country:, cities:, media:, work:, comment:, url:, image:, deadline:, organizer:, eligibility:, budget:, fee:)
  {"category"=>"公開徵件","status"=>"官方來源","updated"=>DATE,"id"=>"competition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"競圖資料庫","region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"deadline"=>deadline,"deadlineLabel"=>work.split("截止 ").last,"deadlineTimezone"=>"Europe/Berlin","deadlinePrecision"=>"datetime","organizer"=>organizer,"eligibility"=>eligibility,"budget"=>budget,"applicationFee"=>fee,"relatedByCity"=>[]}
end

calls = [
  call(n:1,key:"opportunity-2026-emap-residencies-2027",name:"Halle／歐洲｜EMAP 媒體藝術製作駐地 2027",country:"德國／歐洲 / Halle",cities:["Halle","哈雷","Europe","歐洲","Werkleitz"],media:["媒體藝術","機器人藝術","生物藝術"],work:"兩個月製作駐地｜截止 2026.11.06 14:00 CET",comment:"十五個歐洲媒體藝術機構共同提供兩個月製作駐地，支持數位、媒體、機器人與生物藝術家和合作夥伴發展可巡迴的新作；德國節點為 Halle 的 Werkleitz。",url:"https://emare.eu/news-events/open-call-2027",image:"https://emare.eu/media/pages/news-events/open-call-2027/b6b48da6a3-1788443699/banner27-1000x1000.png",deadline:"2026-11-06T14:00:00+01:00",organizer:"European Media Art Platform（含德國 Werkleitz 等 15 個成員機構）",eligibility:"歐盟或符合 Creative Europe 規範國家的數位、媒體、機器人及生物藝術家、雙人組、團體或跨域合作；需與一名合作夥伴共同製作",budget:"申請藝術家 €4,000、合作藝術家 €2,000（藝術雙人組合計 €6,000）、另有 €4,000 製作預算、住宿、旅費與技術設施",fee:"免費"),
  call(n:2,key:"opportunity-2026-atelier-josepha-residency-2027",name:"Ahrenshoop｜Atelier Josepha 波羅的海藝術駐地 2027",country:"德國 / Ahrenshoop",cities:["Ahrenshoop","阿倫斯霍普","Baltic Sea","波羅的海"],media:["藝術駐地","地景研究","跨媒介"],work:"三週駐地｜截止 2026.10.01 23:59 CEST",comment:"邀請藝術家批判性回應波羅的海地區的歷史、環境與當代條件，於秋冬三週駐地中發展繪畫、雕塑、影像、聲音、文字或表演計畫。",url:"https://www.josepha.org/call/",image:"https://image.jimcdn.com/app/cms/image/transf/none/path/sf9cbae73d0f98bfc/backgroundarea/ia626092cf0802513/version/1529604053/image.jpg",deadline:"2026-10-01T23:59:59+02:00",organizer:"Atelier Josepha／ARS BALTICA",eligibility:"無年齡限制的個人藝術家；原則上居住於波羅的海沿岸國家，其他歐洲國家申請者須具明確的波羅的海連結",budget:"獎助 €1,500；免費工作室與住宿、往返旅費，以及最高 €250 材料費",fee:"免費"),
  call(n:3,key:"opportunity-2026-hessian-culture-foundation-travel-residency",name:"Wiesbaden｜黑森文化基金會旅行與國際駐地獎助",country:"德國 / Hessen",cities:["Wiesbaden","威斯巴登","Hessen","New York","Paris","London","Istanbul","Kyoto"],media:["藝術駐地","國際交流","視覺藝術"],work:"2027／2028旅行與駐地獎助｜截止 2026.10.15 23:59 CET",comment:"共十四個旅行、城市駐地與京都結合日本研究名額，讓黑森相關視覺藝術家在三至十二個月的國際工作期間發展新作。",url:"https://www.hkst.de/reise-und-residenzstipendien/bewerbung/",image:"https://www.hkst.de/wp-content/uploads/2024/07/hks-stipendien-1-2300x715.jpg",deadline:"2026-10-15T23:59:59+02:00",organizer:"Hessische Kulturstiftung",eligibility:"出生於黑森、至少自 2025-01-01 起居住黑森，或畢業於黑森藝術學院／相關科系的視覺藝術家；不限年齡，學業須已完成",budget:"旅行獎助每名 €25,000；紐約、巴黎、倫敦一年 €25,000；伊斯坦堡半年 €12,500；京都＋日本旅行半年 €15,000；另可申請最高 €7,700 製作／展示補助",fee:"免費"),
  call(n:4,key:"opportunity-2026-speyer-hans-purrmann-emerging-prize",name:"Speyer｜Hans Purrmann 青年視覺藝術獎",country:"德國 / Speyer",cities:["Speyer","施派爾","Rhineland-Palatinate"],media:["視覺藝術獎","跨媒介","藝術出版"],work:"青年藝術家公開申請｜截止 2026.09.30 23:59 CEST",comment:"獎項鼓勵具有歐洲視野、能連結都會與鄉村經驗的青年視覺藝術家，得主除獎金外並獲得個人圖錄出版。",url:"https://www.speyer.de/de/kultur/bildende-kunst/hans-purrmann-preise/",image:"https://www.speyer.de/de/kultur/bildende-kunst/hans-purrmann-preise/titelbild-2-hans-purrmann-paris-publikation-hans-purrmann-preise-stefan-issig.jpg?cid=kim.eiwv&resize=61ec13%3a1200x630c",deadline:"2026-09-30T23:59:59+02:00",organizer:"Stadt Speyer／Hans Purrmann Stiftung",eligibility:"具歐洲視野與關聯、申請時未滿或不超過 35 歲的青年視覺藝術家；大獎採提名制，不接受自行申請",budget:"青年獎 €6,000，另含個人圖錄出版",fee:"免費"),
  call(n:5,key:"opportunity-2026-enzymkultur-video-paths-roads-2027",name:"德國｜EnzymKultur 2027 錄像藝術：路徑、道路、街道",country:"德國 / Germany",cities:["Germany","德國","EnzymKultur"],media:["錄像藝術","實驗影像","非典型展場"],work:"最長約 20 分鐘錄像徵件｜截止 2026.09.30 23:59 CEST",comment:"徵集實驗、紀錄、敘事或自由形式的錄像作品，入選節目將在車庫、花園與地下室等日常非典型空間放映。",url:"https://enzymkultur.de/news/90-open-call-videokunst-2027-pfade,-wege,-stra%C3%9Fen",image:"https://enzymkultur.de/images/enzymkultur/pfade_wege/projekt/strassen%20wege%20s.png",deadline:"2026-09-30T23:59:59+02:00",organizer:"EnzymKultur e. V.",eligibility:"錄像藝術家；每人最多三件、每件約 20 分鐘以內、MP4；非德語作品須附字幕並持有完整影音權利",budget:"預計每位參展藝術家最高 €100 放映費，須視補助申請結果而定",fee:"免費")
]

def exhibition(n:, key:, name:, country:, cities:, media:, dates:, url:, image:, type:, edition:, organizer:, curator:, venue:, admission:, comment:, statement:)
  {"category"=>"國際展覽","status"=>"官方來源","updated"=>DATE,"id"=>"exhibition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"全球重要展覽","region"=>"全球","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>"#{name}｜#{dates[0]}–#{dates[1]}","comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"exhibitionType"=>type,"exhibitionStatus"=>"已結束／檔案","startDate"=>dates[0],"endDate"=>dates[1],"edition"=>edition,"organizer"=>organizer,"curator"=>curator,"venue"=>venue,"admission"=>admission,"curatorStatement"=>statement,"curatorStatementSource"=>url}
end

exhibitions = [
  exhibition(n:1,key:"exhibition-2025-venice-architecture-intelligens",name:"威尼斯建築雙年展 2025｜Intelligens",country:"義大利 / Venice",cities:["Venice","Venezia","威尼斯","Giardini","Arsenale","Forte Marghera"],media:["建築雙年展","氣候設計","跨域研究"],dates:["2025-05-10","2025-11-23"],url:"https://www.labiennale.org/en/architecture/2025/19th-exhibition",image:"https://static.labiennale.org/files/styles/full_screen_slide/public/architettura/2025/1300x600/fundamentai01.jpg",type:"國際建築雙年展／設計與氣候調查展",edition:"第 19 屆",organizer:"La Biennale di Venezia",curator:"Carlo Ratti",venue:"Giardini、Arsenale、Forte Marghera",admission:"官方售票；主展成人票依官方 2025 公告",comment:"超過七百五十位建築師、工程師、科學家、藝術家與工匠把自然、人工和集體智能匯入同一座設計實驗室，從減碳轉向面對劇烈氣候的調適。",statement:"Intelligens 將拉丁文 gens『人群』置入 intelligence，主張建築必須超越單一 AI 想像，結合自然系統、技術、在地知識與跨世代合作，重新設計已改變的世界。"),
  exhibition(n:2,key:"exhibition-2017-documenta-14-learning-from-athens",name:"documenta 14｜Learning from Athens",country:"德國／希臘 / Kassel–Athens",cities:["Kassel","卡塞爾","Athens","雅典","Piraeus"],media:["documenta","國際調查展","去中心策展"],dates:["2017-04-08","2017-09-17"],url:"https://documenta.de/en/retrospective/documenta-14",image:"https://documenta.de/media/site/fc7c44c520-1744816169/ops-documenta-identity-press-1-_seite_4-1408x-1-1200x630-crop.png",type:"documenta／國際當代藝術五年展",edition:"第 14 屆",organizer:"documenta und Museum Fridericianum gGmbH",curator:"Adam Szymczyk（藝術總監）",venue:"雅典與比雷埃夫斯多處機構及公共空間；卡塞爾 Fridericianum、documenta Halle、Neue Galerie 等",admission:"歷史展覽；當屆依雅典與卡塞爾場館規定",comment:"展覽以雅典和卡塞爾兩個同等重要的百日場域，迫使長期以德國為中心的 documenta 重新面對歐洲危機、殖民視角與知識生產的不平等。",statement:"Learning from Athens 不把雅典當成異國素材，而把雙城展覽設定為連續的美學、經濟、政治與社會實驗，主張世界已無法由單一中心被解釋。"),
  exhibition(n:3,key:"exhibition-2024-sydney-ten-thousand-suns",name:"第 24 屆雪梨雙年展｜Ten Thousand Suns",country:"澳洲 / Sydney",cities:["Sydney","雪梨","White Bay Power Station","Sydney Opera House"],media:["國際雙年展","工業遺址","原住民藝術"],dates:["2024-03-09","2024-06-10"],url:"https://www.biennaleofsydney.art/ten-thousand-suns/",image:"https://www.biennaleofsydney.art/wp-content/uploads/2023/07/BS2024-initial-1110x618-230720.jpg",type:"國際當代藝術雙年展／城市調查展",edition:"第 24 屆",organizer:"Biennale of Sydney",curator:"Cosmin Costinaș、Inti Guerrero（藝術總監）",venue:"White Bay Power Station、AGNSW、Artspace、MCA Australia、Sydney Opera House、UNSW Galleries 等",admission:"免費",comment:"九十六組藝術家以四百件作品把慶典視為抵抗和共同存活的方法，並讓封閉一世紀的 White Bay 發電廠成為新的城市文化空間。",statement:"Ten Thousand Suns 從酷兒抵抗、原住民知識與不同社群的相聚史出發，以歡慶的能量對抗不正義，同時把工業遺產與雪梨公共天際線納入展覽。"),
  exhibition(n:4,key:"exhibition-2024-gwangju-pansori",name:"第 15 屆光州雙年展｜PANSORI：21 世紀的聲景",country:"韓國 / Gwangju",cities:["Gwangju","光州","Yangnim-dong"],media:["國際雙年展","聲景","人類世研究"],dates:["2024-09-07","2024-12-01"],url:"https://www.gwangjubiennale.org/gb/exhibition/past/15.do",image:"https://www.gwangjubiennale.org/resources/img/sns/gb_sns.jpg",type:"國際當代藝術雙年展／聲景與空間調查",edition:"第 15 屆／30 週年",organizer:"Gwangju Biennale Foundation",curator:"Nicolas Bourriaud（藝術總監）",venue:"Gwangju Biennale Exhibition Hall 與 Yangnim-dong 城市場址",admission:"歷史展覽；當屆依官方票務",comment:"七十二位藝術家以韓國敘事音樂『盤索里』作為公共聲音的隱喻，從居所到整顆地球追蹤人類世的空間衝突、遷徙與生態關係。",statement:"PANSORI 將風景同時理解為聲景，讓人、機器、動物、植物與靈性存在的聲音在可步入的歌劇式展覽中交疊，重新想像被邊界與氣候危機切割的共同空間。"),
  exhibition(n:5,key:"exhibition-2022-aichi-still-alive",name:"愛知三年展 2022｜STILL ALIVE",country:"日本 / Aichi",cities:["Aichi","愛知","Nagoya","名古屋","Ichinomiya","Tokoname","Arimatsu"],media:["國際三年展","表演藝術","地方產業"],dates:["2022-07-30","2022-10-10"],url:"https://aichitriennale.jp/2022/en/index.html",image:"https://aichitriennale.jp/2022/img/site.png",type:"國際當代藝術三年展／跨城市展覽",edition:"第 5 屆",organizer:"Aichi Triennale Organizing Committee",curator:"片岡真實 Kataoka Mami（藝術總監）",venue:"Aichi Arts Center、Ichinomiya、Tokoname、Arimatsu",admission:"歷史展覽；主要場館當屆售票，學習與部分城市計畫另行公告",comment:"展覽借用河原溫長期傳訊作品《I AM STILL ALIVE》，以一百組藝術家跨越愛知的工業、陶業、紡織與城市場址，回應疫情後如何繼續生活。",statement:"STILL ALIVE 把『活著』視為持續發送、互相確認的行動；策展從地方產業與傳統文化往返全球危機，追問藝術在戰爭、疫情與災難中的生存可能。")
]

def related(item, candidates)
  keys = item.fetch("cityKeywords", []).map { |x| x.downcase.strip }
  candidates.select { |o| !(keys & o.fetch("cityKeywords", []).map { |x| x.downcase.strip }).empty? }.map { |o| o["id"] }.uniq
end

comp_path = File.join(DATA, "competitions.json")
comp = JSON.parse(File.read(comp_path))
expired_path = File.join(DATA, "expired-20260907.json")
previous_expired = Dir[File.join(DATA, "expired-*.json")].reject { |p| p == expired_path }.flat_map { |p| JSON.parse(File.read(p)).fetch("entries", []) }
existing_expired = File.exist?(expired_path) ? JSON.parse(File.read(expired_path)).fetch("entries", []) : []
today_expired = comp["entries"].select { |e| e["deadline"] && DateTime.parse(e["deadline"]) <= NOW }
archive = (previous_expired + existing_expired + today_expired).uniq { |e| e["dedupeKey"] || e["id"] }
old_keys = previous_expired.map { |e| e["dedupeKey"] || e["id"] }.uniq
removed = archive.count { |e| !old_keys.include?(e["dedupeKey"] || e["id"]) }
comp["entries"].reject! { |e| today_expired.include?(e) || e["updated"] == DATE }
existing_keys = comp["entries"].map { |e| e["dedupeKey"] }
calls.each { |e| comp["entries"] << e unless existing_keys.include?(e["dedupeKey"]) }

all_art_files = Dir[File.join(DATA, "backfill-{july,august,september}-*.json")].reject { |p| p.end_with?("manifest.json") || p.end_with?("20260907.json") }
all_art = all_art_files.flat_map { |p| v=JSON.parse(File.read(p)); v.is_a?(Hash) ? v.fetch("entries", []) : v } + arts
arts.each { |e| e["relatedByCity"] = related(e, comp["entries"]) }
comp["entries"].each { |e| e["relatedByCity"] = related(e, all_art) }

daily = {"meta"=>{"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"total"=>20,"dynamicEntries"=>10,"globalClassicEntries"=>5,"germanClassicEntries"=>5,"source"=>"KÖR Wien、Museum der 1000 Orte 官方頁","selectionPolicy"=>"優先地景、生態、參與、聲光、動態、數位與建築整合作品；不以傳統人物、胸像、騎馬像或基座式紀念碑湊數。","note"=>"9/7 固定 10＋5＋5；另有德國公開徵選 5 則與全球重要展覽 5 篇。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"checkedUniqueSources"=>20,"brokenOrBlockedReplaced"=>0,"rule"=>"發布前逐頁檢查"},"imageAudit"=>{"checkedAt"=>GENERATED_AT,"imageEntries"=>20,"missing"=>0,"rule"=>"官方圖片逐一載入驗證"}},"entries"=>arts}
comp["meta"] = {"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"source"=>"官方主辦機構徵件頁","activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"note"=>"9/7 新增 5 筆有效德國公開徵選；移除 #{removed} 筆逾期案件。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"missingCityKeywords"=>0,"uniqueNewSourcesChecked"=>5,"blockedSourceReplaced"=>0}}

ex_path = File.join(DATA, "exhibitions.json")
ex = JSON.parse(File.read(ex_path)); ex["entries"].reject! { |e| e["updated"] == DATE }
ex_keys = ex["entries"].map { |e| e["dedupeKey"] }; exhibitions.each { |e| ex["entries"] << e unless ex_keys.include?(e["dedupeKey"]) }
ex["meta"] = {"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count { |e| e["status"] == "官方來源" },"imageEntries"=>ex["entries"].count { |e| !e["photo"].to_s.empty? },"note"=>"9/7 新增 5 篇全球重要展覽；全部使用官方來源與可載入圖片。"}

File.write(File.join(DATA, "backfill-september-20260907.json"), JSON.pretty_generate(daily) + "\n")
File.write(comp_path, JSON.pretty_generate(comp) + "\n")
File.write(ex_path, JSON.pretty_generate(ex) + "\n")

sept_path=File.join(DATA,"backfill-september-manifest.json"); sept=JSON.parse(File.read(sept_path)); files=(sept.fetch("files",[])+["backfill-september-20260907.json"]).uniq.sort
sept.merge!({"version"=>"2026-09-07-public-art-r62","generatedAt"=>GENERATED_AT,"files"=>files,"expectedEntries"=>files.length*20,"statementEntries"=>files.length*20,"statementSourceEntries"=>files.length*20,"statementBacklog"=>0,"imageEntries"=>files.length*20,"imageBacklog"=>0,"note"=>"截至 2026-09-07 累計 #{files.length*20} 則；今日新增 20 則公共藝術（10／5／5），已套用非傳統紀念碑選材規則。"}); File.write(sept_path,JSON.pretty_generate(sept)+"\n")
cm_path=File.join(DATA,"competition-manifest.json"); cm=JSON.parse(File.read(cm_path)); cm.merge!({"version"=>"2026-09-07-competition-r38","generatedAt"=>GENERATED_AT,"activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"deadlineTimezoneEntries"=>comp["entries"].count{|e|e["deadlineTimezone"]},"deadlinePrecisionEntries"=>comp["entries"].count{|e|e["deadlinePrecision"]},"cityKeywordEntries"=>comp["entries"].count{|e|!e.fetch("cityKeywords",[]).empty?},"note"=>"2026-09-07 新增 5 則德國公開徵選並移除 #{removed} 則逾期案件。"}); File.write(cm_path,JSON.pretty_generate(cm)+"\n")
em_path=File.join(DATA,"exhibition-manifest.json"); em=JSON.parse(File.read(em_path)); em.merge!({"version"=>"2026-09-07-global-exhibitions-r9","generatedAt"=>GENERATED_AT,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"2026-09-07 新增 5 篇全球重要展覽；全部使用官方來源與可顯示圖片。"}); File.write(em_path,JSON.pretty_generate(em)+"\n")
File.write(expired_path,JSON.pretty_generate({"archivedAt"=>GENERATED_AT,"removedToday"=>removed,"entries"=>archive})+"\n")
File.write(File.join(DATA,"deploy-touch.txt"),"2026-09-07 daily r62 — 20 public artworks + 5 active German open calls + 5 global exhibitions; #{removed} expired calls removed.\n")

puts JSON.pretty_generate({date:DATE, public_art:arts.length, dynamic:arts.count{|e|e["id"].start_with?("current")}, global_classics:arts.count{|e|e["id"].start_with?("classic-global")}, german_classics:arts.count{|e|e["id"].start_with?("classic-german")}, calls:calls.length, exhibitions:exhibitions.length, expired_removed:removed})
