# encoding: UTF-8
require "json"
require "date"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "data")
DATE = "2026-09-06"
GENERATED_AT = "2026-09-06T04:00:00+08:00"
NOW = DateTime.parse(GENERATED_AT)

def art(id:, key:, name:, tier:, country:, cities:, media:, work:, comment:, url:, image:)
  {"category"=>"作品/展覽","status"=>"官方來源","updated"=>DATE,"id"=>id,"dedupeKey"=>key,"name"=>name,"tier"=>tier,"region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>work,"classicImage"=>image,"classicDesc"=>comment,"relatedByCity"=>[]}
end

arts_data = [
  ["current","koer-wir-hier","Nora Mayr 等｜Wir Hier","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Schwendermarkt","Favoriten"],["社會參與","聲音地景","城市步行"],"Wir Hier｜2025","四組城市介入透過市場肖像、QR 聲音、非公民選舉故事與居民歌單，讓『我們在這裡』成為關於歸屬、可見性與共居的開放對話。","https://www.koer.or.at/projects/wir-hier/","https://www.koer.or.at/site/assets/files/14204/00_vorher_a4_wirhier_asmaaiad_c_hannahmayr_15-v1.500x0.jpg"],
  ["current","koer-florestania-im-dritten","Mary Maggic 等｜FLORESTANIA IM DRITTEN","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Village im Dritten"],["生態藝術","回收材料","參與式裝置"],"FLORESTANIA IM DRITTEN｜2025","居民在植物採集、草藥與再生工作坊中把塑膠廢料轉成可步入的森林裝置，將城市廢棄物、內在地景與森林公民權重新連結。","https://www.koer.or.at/projects/florestania-im-dritten/","https://www.koer.or.at/site/assets/files/14099/dsc0400_modified_3.500x0.jpg"],
  ["current","koer-be-a-mensch","Johanna Kandl｜Be a mensch","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Favoriten","Laxenburger Straße"],["壁畫","建築整合","多語公共藝術"],"Be a mensch｜2024","二十七種語言的『人』與唱片圖像沿住宅立面及通廊展開，把 Willi Resetarits 的人權精神轉化為多語、可共同辨識的日常建築表皮。","https://www.koer.or.at/projects/be-a-mensch/","https://www.koer.or.at/site/assets/files/13900/dsc6395_exp_a4.500x0.jpg"],
  ["current","koer-snail-shell-flying-snail","Anna Meyer｜Snail Shell warns Flying Snail","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Meidling","Pohlgasse"],["壁畫","氣候藝術","住宅立面"],"Snail Shell warns Flying Snail｜2024","跨越兩面住宅立面的蝸牛、動物與混種生物構成可移動的居住烏托邦，以幽默圖像追問氣候危機、庇護與低碳建築。","https://www.koer.or.at/projects/schneckenhaus-warnt-flugschnecke-ueberlebenswerk-am-planeten/","https://www.koer.or.at/site/assets/files/13959/c_anna_meyer_04_kleiner.500x0.jpg"],
  ["current","koer-blind-spot-biopatina","Dusts Institute｜Blind Spot","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Heiligenstadt"],["生態介入","生物膜","藝術研究"],"Blind Spot｜2024","團隊在市營住宅立面清出直徑十公尺的圓，反向顯示平常被當成髒污的藻類與真菌，挑戰以潔淨為唯一標準的城市維護。","https://www.koer.or.at/projects/blind-spot/","https://www.koer.or.at/site/assets/files/13841/weisserfleck_53.500x0.jpg"],
  ["current","koer-haunted-landscapes","Claudia Bosse／theatercombinat｜HAUNTED LANDSCAPES","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Favoriten","Hauptbahnhof"],["地景藝術","聲音","行為藝術"],"HAUNTED LANDSCAPES on an unseen wasteland｜2024","在中央車站後方二千五百平方公尺荒地中，以黎明音樂、身體、物件與合唱建立臨時共同體，讀取受傷地景及人與非人行動者的痕跡。","https://www.koer.or.at/projects/haunted-landscape/","https://www.koer.or.at/site/assets/files/13795/auswahl_bosse_2.500x0.jpg"],
  ["current","koer-home-stories-erika-hock","Erika Hock｜Home Stories","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Leopoldstadt","Engerthstraße"],["建築整合","陶瓷","燈光裝置"],"Home Stories｜2024","放大的陶瓷襪子、杯子、鋼管與燈具穿越住宅中庭與戶外角落，以日常物件和 Memphis 色彩為樓層建立既私密又共享的家的尺度。","https://www.koer.or.at/projects/home-stories/","https://www.koer.or.at/site/assets/files/12661/02_dsc9233.500x0.jpg"],
  ["current","koer-wind-clock-barsuglia","Alfredo Barsuglia｜The Wind Clock","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Erdberg","Danube Canal"],["動態裝置","風力藝術","建築整合"],"The Wind Clock or Life is but a Wisp｜2024","屋頂金魚風標以尾鰭驅動三公尺鐘面，時間不再依機械秒針而由風速決定，讓住宅立面成為氣候與當下感知的公共儀器。","https://www.koer.or.at/projects/winduhr-oder-das-leben-ein-hauch/","https://www.koer.or.at/site/assets/files/12652/04.500x0.jpg"],
  ["current","koer-u2-pilgramgasse-davar","Katja Davar｜Swift Messengers","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Pilgramgasse","Wienfluss"],["捷運藝術","琺瑯壁面","生態資訊視覺化"],"Swift Messengers｜U2 Pilgramgasse｜預計 2028","將九條候鳥遷徙路線化成跨樓層像素圖，再以植物與舊鐵路圖交疊，讓氣候、生態網絡與低碳移動共同定義車站。","https://www.koer.or.at/projects/artistic-design-of-the-u2-station-pilgramgasse/","https://www.koer.or.at/site/assets/files/12498/davar_schnitt_wand1_kleiner.500x0.jpg"],
  ["current","koer-u2-matzleinsdorf-collins","Phil Collins｜For Us／Swift Messengers","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Matzleinsdorfer Platz","Favoriten"],["捷運藝術","社區參與","動態裝置"],"For Us／Swift Messengers｜U2 Matzleinsdorfer Platz｜預計 2028","居民影像將形成大型站體壁面，懸吊構件則把鳥群般的移動帶入中庭；公共運輸空間由通道轉成可辨認彼此的城市共同場。","https://www.koer.or.at/projects/artistic-design-of-the-u2-station-matzleinsdorfer-platz/","https://www.koer.or.at/site/assets/files/12484/nl_2_philcollins_matzleinsdorferplatz_a0-2_kleiner.500x0.jpg"],

  ["classic-global","koer-yellow-fog-eliasson","Olafur Eliasson｜Yellow Fog","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Am Hof"],["光藝術","霧裝置","建築立面"],"Yellow Fog｜2008","黃光、霧氣與風沿建築基座持續變化，既把企業立面從穩定物件變成城市氣象，也讓行人以身體感知公共空間的邊界。","https://www.koer.or.at/projects/yellow-fog/","https://www.koer.or.at/site/assets/files/3583/olafur-eliasson-yellow-fog.500x0.jpg"],
  ["classic-global","koer-i-weed-you-weed","Lois Weinberger｜I-weed, YOU-weed","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","MuseumsQuartier"],["文字藝術","植物政治","場域介入"],"I-weed, YOU-weed｜2013","電梯塔上的文字把『雜草』從園藝分類轉成移動、排除與共生的社會隱喻，使城市植物與人的遷徙經驗互相照見。","https://www.koer.or.at/projects/i-weed-you-weed/","https://www.koer.or.at/site/assets/files/1712/lois-weinberger-i-weed-you-weed-01.500x0.jpg"],
  ["classic-global","koer-uniqa-tower-light","Licht Kunst Licht AG｜UNIQA Tower Light Installation","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Donaukanal","UNIQA Tower"],["媒體立面","LED","動態光藝術"],"UNIQA Tower Light Installation｜2005","約四萬顆 LED 將七千平方公尺立面變成可程式控制的城市光幕；動畫不附著於建築，而以時間和移動重寫其夜間體量。","https://www.koer.or.at/projects/uniqa-tower-lichtinstallation/","https://www.koer.or.at/site/assets/files/3116/uniqa-tower-lichtinstallation.500x0.jpg"],
  ["classic-global","koer-turnertempel-memory-site","Iris Andraschek／Hubert Lobnig 等｜Turnertempel Memory Site","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Turnergasse"],["記憶地景","建築遺址","聲音裝置"],"Turnertempel Erinnerungsort｜2011","遺址、植栽、地坪與聲音共同標示被焚毀的猶太會堂；紀念不被收束成單一雕像，而成為可進入、閱讀與停留的城市地景。","https://www.koer.or.at/projects/turnertempel-erinnerungsort/","https://www.koer.or.at/site/assets/files/1761/1206_turnertempel_18.500x0.jpg"],
  ["classic-global","koer-abtauchen-auftauchen","Julie Hayward｜abtauchen／auftauchen","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Löwengasse","Donaukanal"],["通道藝術","建築整合","公共空間"],"abtauchen／auftauchen｜2009","作品介入 Löwengasse 通往多瑙河運河的地下通道，把下沉、穿越與重新浮現的身體經驗轉成光、色與空間的連續變化。","https://www.koer.or.at/projects/abtauchen-auftauchen/","https://www.koer.or.at/site/assets/files/4322/julie-hayward-abtauchen-auftauchen-06.500x0.jpg"],

  ["classic-german","museum-wasser-statistik","Hans-Otto Lohrengel｜Wasser und Statistik","經典檔案庫","德國 / Koblenz",["Koblenz","科布倫茲","Bundesanstalt für Gewässerkunde"],["地景裝置","花崗岩","水文藝術"],"Wasser und Statistik｜2003","花崗岩波形、玄武岩網格與建築內外軸線連成一體，把流動的水與科學統計之間的張力轉化為可步行的地景秩序。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/wasser-und-statistik","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/c15cff370ca03f381edcfe94f72da79949293aaf.jpg"],
  ["classic-german","museum-lichttunnel-bruecke","James Carpenter｜Lichttunnel／Brücke","經典檔案庫","德國 / Berlin",["Berlin","柏林","Auswärtiges Amt","Werderscher Markt"],["光藝術","玻璃裝置","建築通道"],"Lichttunnel／Brücke｜2002","五十多公尺通道以發光玻璃膜與橡木地坪連接外交部新舊建築，讓橋與隧道的雙重意象在行走中交替。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/lichttunnel-brucke","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/a6dd29c4b00332bdf60cb2f8e5bbc556cdaae313.jpg"],
  ["classic-german","museum-zero-latitude-palms","Ulrich Brüschke｜0° Breite","經典檔案庫","德國 / Berlin",["Berlin","柏林","Pankepark","BND"],["地景介入","仿生裝置","監控批判"],"0° Breite (Modified Cellular Towers)｜2012","兩株二十三與二十六公尺高的人工棕櫚模仿通訊基地台偽裝術，在德國情報局與 Pankepark 之間製造熱帶景觀、科技監控與權力可見性的錯位。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/0deg-breite-modified-cellular-towers","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/91f07b0affcf2c0b8538475d5e0d59c78f853573.jpg"],
  ["classic-german","museum-mirrored-planet-system","Rebecca Horn｜Verspiegeltes Planetensystem","經典檔案庫","德國 / Berlin",["Berlin","柏林","Bundesministerium für Verkehr"],["動態藝術","鏡面裝置","建築中庭"],"Verspiegeltes Planetensystem｜2000","二十一件馬達驅動鏡面物件分布於雙層採光中庭，以精密轉動把天空、建築與行人切成不斷遷移的光學星系。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/verspiegeltes-planetensystem","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/0b87f49334b179eae810fb8ad5ebd8a599a93afb.jpg"],
  ["classic-german","museum-schnittstelle-greenhouse","Karin Rosenberg｜Schnittstelle","經典檔案庫","德國 / Berlin",["Berlin","柏林","Bundesministerium für Ernährung und Landwirtschaft"],["剪紙裝置","植物圖像","建築整合"],"Schnittstelle (Gewächshaus, Papaya, Tamarinde)｜2013","溫室、木瓜與羅望子三組大型剪紙懸於農業部中庭，將植物分類、全球貿易與自然／文化邊界編成透光的圖像網絡。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/schnittstelle-gewachshaus-papaya-tamarinde","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/d238dceebb78e7f482ef50fe390029b485958848.jpg"]
]

arts = arts_data.each_with_index.map do |a, i|
  group,key,title,tier,country,cities,media,work,comment,url,image = a
  n = group == "current" ? i + 1 : group == "classic-global" ? i - 9 : i - 14
  art(id:"#{group}-#{DATE}-#{format('%02d',n)}",key:"art-#{DATE}-#{key}",name:"#{format('%02d',n)}｜#{title}",tier:tier,country:country,cities:cities,media:media,work:work,comment:comment,url:url,image:image)
end

def call(n:, key:, name:, cities:, media:, work:, comment:, url:, image:, deadline:, organizer:, eligibility:, budget:, fee:)
  {"category"=>"公開徵件","status"=>"官方來源","updated"=>DATE,"id"=>"competition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"競圖資料庫","region"=>"西方","country"=>"德國 / #{cities.first}","cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"deadline"=>deadline,"deadlineLabel"=>work.split("截止 ").last,"deadlineTimezone"=>"Europe/Berlin","deadlinePrecision"=>"date","organizer"=>organizer,"eligibility"=>eligibility,"budget"=>budget,"applicationFee"=>fee,"relatedByCity"=>[]}
end

calls = [
  call(n:1,key:"opportunity-2026-hbk-braunschweig-projects-27-28",name:"Braunschweig｜HBK Projects 2027／28 藝術家獎助",cities:["Braunschweig","不倫瑞克"],media:["藝術駐地","聲音藝術","視覺藝術"],work:"十二個月藝術家獎助｜截止 2026.10.04",comment:"提供兩名聲音藝術與五名視覺藝術家一年期創作環境、工作室住宅及校園交流，以跨領域實踐連結藝術研究與教學。",url:"https://www.hbk-bs.de/bs-projects-english/call-and-application-1/",image:"https://www.hbk-bs.de/fileadmin/_processed_/0/5/csm_Design_ohne_Titel_9__b1a6ea9425.png",deadline:"2026-10-04T23:59:59+02:00",organizer:"Hochschule für Bildende Künste Braunschweig",eligibility:"完成藝術學位、具專業創作與展覽紀錄；最後學業完成時間須符合官方 2016-04-01 至 2023-04-01 條件",budget:"每月 €1,600、十二個月；免租工作室住宅，另有計畫與旅費補助；住戶每月自付 €250 雜費",fee:"免費"),
  call(n:2,key:"opportunity-2026-dresden-bsz-electrical-art-building",name:"Dresden｜電氣職業學校 Kunst am Bau",cities:["Dresden","德勒斯登"],media:["建築藝術","公共藝術","場域特定"],work:"兩階段校園公共藝術競賽｜截止 2026.10.05",comment:"為新電氣職業學校提出能被感官經驗、回應校園使用並強化場所認同的室內或戶外作品，最多實現兩件。",url:"https://www.stesad.de/kunst-am-bau-wettbewerb-fuer-das-neue-bsz-elektrotechnik/",image:"https://www.stesad.de/wp-content/uploads/2026/06/BSZET_Aussenraum_Eingang_RBZ_NEU_mittel.jpg",deadline:"2026-10-05T23:59:59+02:00",organizer:"KID, Kommunale Immobilien Dresden GmbH & Co. KG／STESAD",eligibility:"居住於歐盟的專業藝術家、藝術家團隊；第一階段以德文提交資格、作品與履歷 PDF",budget:"實現總預算最高 €330,000 含稅；競賽獎金共 €30,000；第二階段合格提案各 €3,800",fee:"免費"),
  call(n:3,key:"opportunity-2027-frechen-graphic-triennale-21",name:"Frechen｜第 21 屆國際版畫三年展",cities:["Frechen","弗雷興","Cologne","科隆"],media:["版畫","國際三年展","藝術獎"],work:"國際當代版畫徵件｜截止 2026.09.29",comment:"以傳統木刻、網版、蝕刻到電腦輸出等廣義版畫為範圍，重點不是複製技術，而是媒材如何形成作品的內容與形式力量。",url:"https://kunstverein-frechen.de/call-for-entries-xxi-grafik-triennale-2027/",image:"https://kunstverein-frechen.de/wp-content/uploads/2026/07/GT27_3.jpg",deadline:"2026-09-29T23:59:59+02:00",organizer:"Kunstverein zu Frechen e. V.／Stadt Frechen",eligibility:"全球專業藝術家；作品須屬版畫領域，傳統與新式印製技術均可，三維或單件作品須具版畫關聯",budget:"一獎 €3,000、二獎 €2,000、三獎 €1,500；在學青年獎 €1,000、觀眾獎 €200",fee:"€40"),
  call(n:4,key:"opportunity-2027-kuenstlergut-proesitz-symposium",name:"Grimma／Prösitz｜母親藝術家雕塑與裝置獎助",cities:["Grimma","格里馬","Prösitz","Leipzig"],media:["雕塑","裝置藝術","戶外創作"],work:"四週創作研討與親子駐地｜截止 2026.11.30",comment:"為同時身為母親的專業女性藝術家提供四週工作坊、住宿與十二歲以下兒童照顧，使雕塑、裝置與物件創作能在照護現實中持續。",url:"https://www.kuenstlergut-proesitz.de/symposium/?SHC=1",image:"https://www.kuenstlergut-proesitz.de/pages/kuenstlergut/fotos/banner/symposium.jpg",deadline:"2026-11-30T23:59:59+01:00",organizer:"Künstlergut Prösitz e. V.",eligibility:"從事雕塑、立體、裝置或物件藝術的專業女性藝術家，且同時為母親；可攜十二歲以下子女",budget:"獎助 €500；四週住宿與兒童照顧免費，另依個案提供材料與組織協助，後續有聯展與共同圖錄",fee:"免費；僅接受紙本資料"),
  call(n:5,key:"opportunity-2026-steiger-gallery-wassergarten",name:"Schiffweiler｜Steiger Gallery Wassergarten 地景提案",cities:["Schiffweiler","希夫韋勒","Reden","Saarland"],media:["地景藝術","光／聲音藝術","互動裝置"],work:"礦業水花園永久公共藝術概念｜截止 2026.09.13",comment:"在舊 Reden 礦區的水池、濕地、鋼構與石牆提出永久介入，回應工業史、轉型、生態與場址未來，媒介包含光、聲音、動態與 Land Art。",url:"https://steiger-gallery.de/call-for-concepts/",image:"https://steiger-gallery.de/wp-content/uploads/2026/07/Wall_03.jpg",deadline:"2026-09-13T23:59:59+02:00",organizer:"Steiger Gallery／Industriekultur Saar GmbH",eligibility:"各國新銳或成熟藝術家，類型不限；提案須可由藝術家自行實施並適合戶外、氣候與公共使用",budget:"藝術家費、製作與安裝總成本 €2,000–€60,000；第二階段深化提案費最高 €1,000",fee:"免費")
]

def exhibition(n:, key:, name:, country:, cities:, media:, dates:, url:, image:, type:, edition:, organizer:, curator:, venue:, admission:, comment:, statement:)
  {"category"=>"國際展覽","status"=>"官方來源","updated"=>DATE,"id"=>"exhibition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"全球重要展覽","region"=>"全球","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>"#{name}｜#{dates[0]}–#{dates[1]}","comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"exhibitionType"=>type,"exhibitionStatus"=>"已結束／檔案","startDate"=>dates[0],"endDate"=>dates[1],"edition"=>edition,"organizer"=>organizer,"curator"=>curator,"venue"=>venue,"admission"=>admission,"curatorStatement"=>statement,"curatorStatementSource"=>url}
end

exhibitions = [
  exhibition(n:1,key:"exhibition-2025-helsinki-shelter",name:"Helsinki Biennial 2025｜Shelter",country:"芬蘭 / Helsinki",cities:["Helsinki","赫爾辛基","Vallisaari","Esplanade"],media:["島嶼雙年展","地景藝術","生態藝術"],dates:["2025-06-08","2025-09-21"],url:"https://helsinkibiennaali.fi/en/hb25/",image:"https://evermade-helsinkibiennaali-phase2-website.s3.eu-north-1.amazonaws.com/wp-content/uploads/2024/12/03010942/HB25_Sammalkuva_Vaaka_Low.jpg",type:"國際當代藝術雙年展／島嶼地景展",edition:"第 3 屆",organizer:"HAM Helsinki Art Museum／City of Helsinki",curator:"Kati Kivinen、Blanca de la Torre",venue:"Vallisaari Island、Esplanade Park、HAM Helsinki Art Museum",admission:"雙年展免費；Vallisaari 船票另計",comment:"三十七組藝術家從長期少人居住的 Vallisaari 島出發，把動物、植物、真菌、水與礦物置於人類之前，重新想像庇護與共同生存。",statement:"Shelter 不只是一個遮蔽空間，而是所有生命可以繁衍的照護關係；策展藉場域作品把生態倫理從論述推向具體行動。"),
  exhibition(n:2,key:"exhibition-2022-documenta-fifteen-lumbung",name:"documenta fifteen｜lumbung",country:"德國 / Kassel",cities:["Kassel","卡塞爾","Fulda","Bettenhausen"],media:["documenta","社會實踐","集體策展"],dates:["2022-06-18","2022-09-25"],url:"https://documenta-fifteen.de/en/about/",image:"https://documenta-fifteen.de/wp-content/uploads/2021/04/Sharing-image-scaled.jpg",type:"documenta／國際文件展系譜",edition:"第 15 屆",organizer:"documenta und Museum Fridericianum gGmbH",curator:"ruangrupa（藝術總監）與 lumbung 成員",venue:"Kassel 32 處場址與城市社群網絡",admission:"主要場館需購票；部分公共計畫免費",comment:"ruangrupa 以印尼共同穀倉 lumbung 為制度模型，讓集體決策、資源共享與長期社群關係取代單向度的百日大型展演。",statement:"展覽把卡塞爾視為 ekosistem 而非容器，使知識、金錢、時間與空間都成為可共同累積和公平分配的公共資源。"),
  exhibition(n:3,key:"exhibition-2024-yokohama-wild-grass",name:"第 8 屆橫濱三年展｜野草：我們的生命",country:"日本 / Yokohama",cities:["Yokohama","橫濱","Minatomirai","BankART"],media:["國際三年展","城市展覽","跨媒介"],dates:["2024-03-15","2024-06-09"],url:"https://www.yokohamatriennale.jp/2024/en/outline/",image:"https://www.yokohamatriennale.jp/2024/wp-content/uploads/2023/11/Thumbnail.png",type:"國際當代藝術三年展",edition:"第 8 屆",organizer:"City of Yokohama／Yokohama Arts Foundation／NHK／The Asahi Shimbun 等",curator:"Liu Ding、Carol Yinghua Lu（藝術總監）",venue:"Yokohama Museum of Art、Former Daiichi Bank Yokohama Branch、BankART KAIKO 等",admission:"主要展區購票；城市合作計畫依場址",comment:"展名借用魯迅《野草》，拒絕把改變寄託於英雄敘事，而在日常生命如野草般被忽視的韌性中尋找面對戰爭、氣候與不寬容的芽。",statement:"策展把國際視野與地方生活並置，主張藝術只有在全球連結與城市根系同時存在時，才可能真正介入我們的生活。"),
  exhibition(n:4,key:"exhibition-2021-liverpool-stomach-port",name:"Liverpool Biennial 2021｜The Stomach and the Port",country:"英國 / Liverpool",cities:["Liverpool","利物浦","Bluecoat","Tate Liverpool"],media:["國際雙年展","公共藝術","聲音與影像"],dates:["2021-03-20","2021-06-06"],url:"https://www.biennial.com/previous-biennials/edition-2021/",image:"https://www.biennial.com/wp-content/uploads/2023/03/dr-lakra-ship.jpg",type:"國際當代藝術雙年展",edition:"第 11 屆",organizer:"Liverpool Biennial",curator:"Manuela Moscoso",venue:"Bluecoat、FACT、Open Eye Gallery、Tate Liverpool、歷史建築與戶外場址",admission:"免費",comment:"以胃、孔隙與親屬關係為三個入口，將身體視為不斷被環境塑造、也反過來塑造環境的流動系統，呼應港口的交換與控制史。",statement:"展覽以非西方思考挑戰封閉個體，將污染、知識流通與超越人類的親屬關係放入城市各處，使利物浦港成為身體與世界互滲的模型。"),
  exhibition(n:5,key:"exhibition-2023-sharjah-biennial-15",name:"Sharjah Biennial 15｜Thinking Historically in the Present",country:"阿拉伯聯合大公國 / Sharjah",cities:["Sharjah","沙迦","Al Dhaid","Kalba","Khorfakkan"],media:["國際雙年展","後殖民研究","場域活化"],dates:["2023-02-07","2023-06-11"],url:"https://www.sharjahart.org/en/press/details/sharjah-biennial-15-continues-its-extensive-programme-of-performances-films",image:"https://www.sharjahart.org/images/Thumbnail/c_press.jpg",type:"國際當代藝術雙年展／國際調查展",edition:"第 15 屆／30 週年",organizer:"Sharjah Art Foundation",curator:"Okwui Enwezor 構想；Hoor Al Qasimi 策展與工作小組",venue:"沙迦酋長國 5 城鎮、19 處歷史與再利用場址",admission:"免費",comment:"超過一百五十組藝術家與三百件作品跨越五座城鎮，把歷史遺址、改造建築和當代委託作品串成後殖民世界的多點調查。",statement:"Hoor Al Qasimi 延展 Okwui Enwezor 的構想，以『在當下進行歷史思考』抵抗單一現代性，讓被壓抑的過去成為重新理解現在的工具。")
]

def related(item, candidates)
  keys = item.fetch("cityKeywords", []).map { |x| x.downcase.strip }
  candidates.select { |o| !(keys & o.fetch("cityKeywords", []).map { |x| x.downcase.strip }).empty? }.map { |o| o["id"] }.uniq
end

comp_path = File.join(DATA, "competitions.json")
comp = JSON.parse(File.read(comp_path))
expired_path = File.join(DATA, "expired-20260906.json")
previous_expired = Dir[File.join(DATA, "expired-*.json")].reject { |p| p == expired_path }.flat_map { |p| JSON.parse(File.read(p)).fetch("entries", []) }
existing_expired = File.exist?(expired_path) ? JSON.parse(File.read(expired_path)).fetch("entries", []) : []
today_expired = comp["entries"].select { |e| e["deadline"] && DateTime.parse(e["deadline"]) <= NOW }
archive = (previous_expired + existing_expired + today_expired).uniq { |e| e["dedupeKey"] || e["id"] }
old_keys = previous_expired.map { |e| e["dedupeKey"] || e["id"] }.uniq
removed = archive.count { |e| !old_keys.include?(e["dedupeKey"] || e["id"]) }
comp["entries"].reject! { |e| today_expired.include?(e) || e["updated"] == DATE }
existing_keys = comp["entries"].map { |e| e["dedupeKey"] }
calls.each { |e| comp["entries"] << e unless existing_keys.include?(e["dedupeKey"]) }

all_art_files = Dir[File.join(DATA, "backfill-{july,august,september}-*.json")].reject { |p| p.end_with?("manifest.json") || p.end_with?("20260906.json") }
all_art = all_art_files.flat_map { |p| v=JSON.parse(File.read(p)); v.is_a?(Hash) ? v.fetch("entries", []) : v } + arts
arts.each { |e| e["relatedByCity"] = related(e, comp["entries"]) }
comp["entries"].each { |e| e["relatedByCity"] = related(e, all_art) }

daily = {"meta"=>{"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"total"=>20,"dynamicEntries"=>10,"globalClassicEntries"=>5,"germanClassicEntries"=>5,"source"=>"KÖR Wien、Museum der 1000 Orte 官方頁","selectionPolicy"=>"優先地景、生態、參與、聲光、動態與建築整合作品；不以傳統人物、胸像、騎馬像或基座式紀念碑湊數。","note"=>"9/6 固定 10＋5＋5；另有德國公開徵選 5 則與全球重要展覽 5 篇。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"checkedUniqueSources"=>20,"brokenOrBlockedReplaced"=>0,"rule"=>"實際瀏覽器逐頁檢查"},"imageAudit"=>{"checkedAt"=>GENERATED_AT,"imageEntries"=>20,"missing"=>0,"rule"=>"官方直接圖片逐一載入驗證"}},"entries"=>arts}
comp["meta"] = {"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"source"=>"官方主辦機構徵件頁","activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"note"=>"9/6 新增 5 筆有效德國公開徵選；移除 #{removed} 筆逾期案件。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"missingCityKeywords"=>0,"uniqueNewSourcesChecked"=>5,"blockedSourceReplaced"=>0}}

ex_path = File.join(DATA, "exhibitions.json")
ex = JSON.parse(File.read(ex_path)); ex["entries"].reject! { |e| e["updated"] == DATE }
ex_keys = ex["entries"].map { |e| e["dedupeKey"] }; exhibitions.each { |e| ex["entries"] << e unless ex_keys.include?(e["dedupeKey"]) }
ex["meta"] = {"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count { |e| e["status"] == "官方來源" },"imageEntries"=>ex["entries"].count { |e| !e["photo"].to_s.empty? },"note"=>"9/6 新增 5 篇全球重要展覽；全部使用可開啟官方來源與可載入圖片。"}

File.write(File.join(DATA, "backfill-september-20260906.json"), JSON.pretty_generate(daily) + "\n")
File.write(comp_path, JSON.pretty_generate(comp) + "\n")
File.write(ex_path, JSON.pretty_generate(ex) + "\n")

sept_path=File.join(DATA,"backfill-september-manifest.json"); sept=JSON.parse(File.read(sept_path)); files=(sept.fetch("files",[])+["backfill-september-20260906.json"]).uniq.sort
sept.merge!({"version"=>"2026-09-06-public-art-r60","generatedAt"=>GENERATED_AT,"files"=>files,"expectedEntries"=>files.length*20,"statementEntries"=>files.length*20,"statementSourceEntries"=>files.length*20,"statementBacklog"=>0,"imageEntries"=>files.length*20,"imageBacklog"=>0,"note"=>"截至 2026-09-06 累計 #{files.length*20} 則；今日新增 20 則公共藝術（10／5／5），已套用非傳統紀念碑選材規則。"}); File.write(sept_path,JSON.pretty_generate(sept)+"\n")
cm_path=File.join(DATA,"competition-manifest.json"); cm=JSON.parse(File.read(cm_path)); cm.merge!({"version"=>"2026-09-06-competition-r37","generatedAt"=>GENERATED_AT,"activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"deadlineTimezoneEntries"=>comp["entries"].count{|e|e["deadlineTimezone"]},"deadlinePrecisionEntries"=>comp["entries"].count{|e|e["deadlinePrecision"]},"cityKeywordEntries"=>comp["entries"].count{|e|!e.fetch("cityKeywords",[]).empty?},"note"=>"2026-09-06 新增 5 則德國公開徵選並移除 #{removed} 則今日逾期案件。"}); File.write(cm_path,JSON.pretty_generate(cm)+"\n")
em_path=File.join(DATA,"exhibition-manifest.json"); em=JSON.parse(File.read(em_path)); em.merge!({"version"=>"2026-09-06-global-exhibitions-r8","generatedAt"=>GENERATED_AT,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"2026-09-06 新增 5 篇全球重要展覽；全部使用官方來源與可顯示圖片。"}); File.write(em_path,JSON.pretty_generate(em)+"\n")
File.write(expired_path,JSON.pretty_generate({"archivedAt"=>GENERATED_AT,"removedToday"=>removed,"entries"=>archive})+"\n")
File.write(File.join(DATA,"deploy-touch.txt"),"2026-09-06 daily r60 — 20 public artworks + 5 active German open calls + 5 global exhibitions; non-monument selection policy applied; #{removed} expired calls removed.\n")
