# encoding: UTF-8
require "json"
require "date"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "data")
DATE = "2026-09-08"
GENERATED_AT = "2026-09-08T04:00:00+08:00"
NOW = DateTime.parse(GENERATED_AT)

def art(id:, key:, name:, tier:, country:, cities:, media:, work:, comment:, url:, image:)
  {"category"=>"作品/展覽","status"=>"官方來源","updated"=>DATE,"id"=>id,"dedupeKey"=>key,"name"=>name,"tier"=>tier,"region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>work,"classicImage"=>image,"classicDesc"=>comment,"relatedByCity"=>[]}
end

koer = "https://www.koer.or.at"
art_rows = [
  ["current","koer-alte-rollt-auf-zeit","IG Bildende Kunst、ZAK｜老婦人準時上路","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Westbahnhof","MuseumsQuartier"],["行動藝術","參與式藝術","城市遊行"],"Die Alte rollt auf Zeit｜2026","藝術工作者以五公里的移動行動穿越維也納，從西站、Urban-Loritz-Platz 到博物館區，把年齡、勞動與公共文化政策轉化為一場可被城市共同看見的團結路線。","#{koer}/projects/die-alte-rollt-auf-zeit/","#{koer}/site/assets/files/15471/02_visual-vertical-ohnelogos-100.500x0.jpg"],
  ["current","koer-chara","Kris Lemsalu｜Chará","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Graben"],["公共雕塑","女性主義藝術","身體政治"],"Chará｜2023","一座介於門、身體與神話生物之間的雕塑進入 Graben 商業街，以開放的孔洞和繁複材質打斷秩序整齊的歷史街景，讓性別、慾望與城市觀看彼此穿透。","#{koer}/projects/kunstplatz-graben-2023/","#{koer}/site/assets/files/12305/kleiner_koer_graben2023_-5998.500x0.jpg"],
  ["current","koer-level-zero","The Poetry of Donau City｜從零層出發","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Donau City"],["城市研究","聲音藝術","場域介入"],"Aus der Null-Ebene｜2023","計畫從多層化的 Donau City 地面系統出發，以藝術行動讀取辦公塔樓、平台、風與人的流動，讓看似無人的現代城市顯露日常使用與詩性縫隙。","#{koer}/projects/aus-der-null-ebene/","#{koer}/site/assets/files/12196/kleiner_nullebene_300dpi.500x0.jpg"],
  ["current","koer-sleeping-horse","Heike Mutter、Ulrich Genth｜沉睡的馬","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Reumannplatz"],["公共雕塑","互動藝術","城市地景"],"Sleeping Horse｜2023","躺臥的馬不再把英雄高舉於基座，而以疲憊、脆弱又可親近的姿態貼近廣場生活，反轉傳統騎馬紀念物的權力視角。","#{koer}/projects/sleeping-horse/","#{koer}/site/assets/files/12231/kleiner_koer_muttergenth_pferd_reumannplatz_-5459_iris_ranzinger.500x0.jpg"],
  ["current","koer-permafurie","Natalie Deewan｜永久狂怒／香水店","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["文字藝術","氣味藝術","公共介入"],"PERMAFURIE／PARFUMERIE｜2023","作品以近似店招與香氛品牌的文字錯位，把被商品化的感官經驗導向城市裡持續存在的憤怒；語言成為同時誘人又帶刺的公共表面。","#{koer}/projects/permafurie-parfumerie/","#{koer}/site/assets/files/12139/kleiner_permafurie_22_5_2023_montage_ohne_neu_rgb_cut_hell.500x0.jpg"],
  ["current","koer-siehe-da","Heimo Zobernig｜看，那裡","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["場域裝置","建築介入","觀念藝術"],"siehe da｜2023","簡短命令式語句把觀看本身變成作品：觀眾被提醒停下來辨認平時略過的建築、空隙與城市秩序，公共藝術不再只是新增物件，而是重新分配注意力。","#{koer}/projects/siehe-da/","#{koer}/site/assets/files/12164/kleiner_siehe_da_jalalieh_zimmermann_100_fullsize.500x0.jpg"],
  ["current","koer-cargo-vienna","Tracing Spaces｜CARGO VIENNA","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Nordwestbahnhof"],["城市研究","行動藝術","工業地景"],"CARGO VIENNA｜2023","藝術團隊以巴士、路線與現場敘事進入即將改造的西北貨運站，將物流地景、勞動記憶和大型都市更新放在同一條移動視線中。","#{koer}/projects/cargo-vienna/","#{koer}/site/assets/files/12183/sujet_kleiner.500x0.jpg"],
  ["current","koer-zeichen-der-zeit","KÖR Wien｜時代的標記","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["聲音導覽","歷史研究","城市步行"],"Zeichen der Zeit｜2023","聲音導覽帶領觀眾辨認 1934 至 1945 年間維也納公共藝術留下的政治痕跡，讓街道成為可以邊走邊校讀權力、宣傳與遺忘的檔案。","#{koer}/projects/zeichen-der-zeit/","#{koer}/site/assets/files/12069/planauschnitt_01.500x0.jpg"],
  ["current","koer-wandertag-2","Christiane Peschek 等｜漫遊日第二版","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["城市步行","行為藝術","跨媒介"],"Wandertag Edition 2｜2023","四組藝術家以共同步行、聲音、表演和偶發遭遇重新編排行走節奏，使參與者從交通效率中抽離，將城市邊緣轉成臨時展場。","#{koer}/projects/wandertag-edition-2/","#{koer}/site/assets/files/12090/01_coverbild_gesamt_kleiner.500x0.jpg"],
  ["current","koer-common-kingdom","Agnes Bakucz Canário｜共同王國","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["行為藝術","身體地景","社會參與"],"A COMMON KINGDOM｜2023","作品以身體、群聚與切割意象討論公共空間裡的共同性：兩道平行切口既像邊界，也像能被重新縫合的關係。","#{koer}/projects/a-common-kingdom/","#{koer}/site/assets/files/12041/a_common_kingdom_ankuendigung_1_c_josefin_sternbauer-_2022-1.500x0.jpg"],
  ["classic-global","koer-lillies","Markus Linnenbrink｜首先思考百合","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["色彩裝置","建築整合","公共藝術"],"FIRSTOFALLPONDERTHELILLIES｜2023","高彩度色帶沿著建築與通行空間展開，把日常動線變成可步入的繪畫；標題以百合的停頓感對抗城市速度。","#{koer}/projects/zuallerersterwaegedielilien/","#{koer}/site/assets/files/11850/230309_wienerlinien_linnebrink_-3537.500x0.jpg"],
  ["classic-global","koer-franz-west-esteplatz","Franz West｜Esteplatz 五件戶外雕塑","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Esteplatz"],["公共雕塑","戶外裝置","抽象藝術"],"Franz West on Esteplatz｜2022","五件帶著手作痕跡與不穩定輪廓的雕塑散落廣場，使抽象形式不再是遙遠物件，而成為行走、停留與身體尺度的鄰居。","#{koer}/projects/franz-west-on-esteplatz/","#{koer}/site/assets/files/12014/franz-west-fuenfteilige-aussenskulptur_0425.500x0.jpg"],
  ["classic-global","koer-heat","Anna Witt｜熱","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Mitterhofergasse","MIHO"],["影像藝術","熱感攝影","社會參與"],"HEAT｜2022","青少年的身體活動經熱感鏡頭轉為流動色塊並投映到社區中心，讓生理溫度、社會關係與城市共同體的『熱度』同時可見。","#{koer}/projects/heat/","#{koer}/site/assets/files/12005/still_heat_2_kopie.500x0.jpg"],
  ["classic-global","koer-larger-forest","Oktavia Schreiner｜更大的森林","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["生態藝術","地景裝置","城市自然"],"Der größere Wald｜2022","作品以森林作為超越單株樹木的關係網，讓公共藝術關注土壤、庇蔭、氣候與城市棲地，而非以單一物件佔據空間。","#{koer}/projects/der-groessere-wald/","#{koer}/site/assets/files/11995/schreiner_4.500x0.jpg"],
  ["classic-global","koer-city-tours","Boris Sieverts｜城市旅行社","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["城市探索","導覽藝術","地景研究"],"Büro für Städtereisen｜2022","藝術家以非典型旅行社的方法帶人穿越基礎設施、荒地與城市接縫，把沒有被觀光命名的地帶轉成理解都市生成的核心景觀。","#{koer}/projects/buero-fuer-staedtereisen/","#{koer}/site/assets/files/11965/sieverts_urbanize_camilla_reimitz-wachberger-_2022_1.500x0.jpg"],
  ["classic-german","museum-lichtwald","Günter Ferdinand Ris｜光之林","經典檔案庫","德國 / Bonn",["Bonn","波昂","Palais Schaumburg","Bundeskanzleramt"],["光藝術","動力裝置","建築整合"],"Lichtwald｜1976","垂直光體在建築環境中形成可穿行的人工樹林，以節奏、反射與亮度取代傳統紀念物的厚重體量。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/lichtwald","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/8bad278078b61e6c4035991fc7e05d9d2fc4dd0d.jpg"],
  ["classic-german","museum-mondfluss","Rebecca Horn｜月河","經典檔案庫","德國 / Bonn",["Bonn","波昂","World Conference Center Bonn"],["水景藝術","光藝術","場域裝置"],"Mondfluss｜1997","水、月光般的反射與機械節奏把議政建築周邊轉為感知地景，柔化制度空間，也讓時間以緩慢流動的形式被看見。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/mondfluss","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/8cf1741c939efa4d06799b264994e6c3586f0e01.jpg"],
  ["classic-german","museum-wasserwald","Norbert Kricke｜大水林","經典檔案庫","德國 / Nürnberg",["Nürnberg","紐倫堡","Bundesagentur für Arbeit"],["水景藝術","線性雕塑","建築整合"],"Großer Wasserwald｜1973","纖細金屬線與噴水把空氣描成一座透明森林；作品讓水的運動成為建築前景，而不是固定紀念形體。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/grosser-wasserwald","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/1ad06871cc39e4214adeb09cdca5bcf1f3ca2ced.jpg"],
  ["classic-german","museum-ulmer-farblabor","Michael Jäger｜烏爾姆色彩實驗室","經典檔案庫","德國 / Ulm",["Ulm","烏爾姆","Science Park II"],["色彩裝置","建築整合","研究空間"],"Ulmer Farblabor｜2011","色彩系統與科研建築的表面、動線互相校準，使工作場所成為可變的視覺實驗室，也將實驗精神從室內延伸至公共通道。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/ulmer-farblabor","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/5e0b22f8553e4ded9e66ace60bf78e0dce2b1ba8.jpg"],
  ["classic-german","museum-water-lenses","Adolf Luther｜水－透鏡整合：向莫內致敬","經典檔案庫","德國 / Bonn",["Bonn","波昂","Bundestag"],["水景藝術","光學藝術","地景裝置"],"Integration Wasser-Linsen｜1988","水面與透鏡把天空、建築和行人的影像拆解為流動光場，以觀看的不確定性向莫內致敬，也將建築庭院轉成持續變化的感知地景。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/integration-wasser-linsen-hommage-an-monet","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/dc19cf45fc639388b49f6baff0d8207fb10c27db.jpg"]
]

arts = art_rows.each_with_index.map do |a, i|
  group,key,title,tier,country,cities,media,work,comment,url,image = a
  number = group == "current" ? i + 1 : group == "classic-global" ? i - 9 : i - 14
  art(id:"#{group}-#{DATE}-#{format('%02d',number)}",key:"art-#{DATE}-#{key}",name:"#{format('%02d',number)}｜#{title}",tier:tier,country:country,cities:cities,media:media,work:work,comment:comment,url:url,image:image)
end

def call(n:, key:, name:, cities:, media:, work:, comment:, url:, image:, deadline:, organizer:, eligibility:, budget:)
  {"category"=>"公開徵件","status"=>"官方來源","updated"=>DATE,"id"=>"competition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"競圖資料庫","region"=>"西方","country"=>"德國","cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"deadline"=>deadline,"deadlineLabel"=>work.split("截止 ").last,"deadlineTimezone"=>"Europe/Berlin","deadlinePrecision"=>"datetime","organizer"=>organizer,"eligibility"=>eligibility,"budget"=>budget,"applicationFee"=>"免費","relatedByCity"=>[]}
end

calls = [
  call(n:1,key:"opportunity-2026-goethe-ikf-round-2",name:"慕尼黑／國際共同製作基金第二輪",cities:["Munich","München","慕尼黑","Germany","德國"],media:["跨國共製","表演藝術","音樂"],work:"最長 12 個月共製｜截止 2026.10.12 23:59 CET",comment:"由德國境外藝術家或團隊與德國合作方共同提出，支持音樂、舞蹈、戲劇與跨域現場藝術的國際共同製作，強調平等分工與可持續合作。",url:"https://www.goethe.de/en/kul/foe/int.html",image:"https://www.goethe.de/resources/files/jpg1361/tanz_ikf_intro-formatkey-avif-w1920.jpg",deadline:"2026-10-12T23:59:00+01:00",organizer:"Goethe-Institut e.V.",eligibility:"德國境外（不含奧地利、瑞士）的藝術家、團隊或機構，須與德國藝術家、團隊或機構共同製作",budget:"依核定計畫補助藝術家費、旅費、製作費與國際合作支出"),
  call(n:2,key:"opportunity-2026-berlin-global-exchange-2027",name:"柏林／2027 全球文化交流獎助",cities:["Berlin","柏林","Germany","德國","Global","全球"],media:["國際交流","藝術駐地","跨領域"],work:"全球 1–3 個月交流｜截止 2026.09.15 14:00 CEST",comment:"支持居住柏林的專業藝術家與海外夥伴進行一至三個月的藝術／策展合作，涵蓋所有藝術門類，鼓勵在目的地建立實質且持續的專業關係。",url:"https://www.berlin.de/sen/kultur/en/funding/funding-programmes/international-cultural-exchange/artikel.236096.en.php",image:"https://www.berlin.de/i9f/r1/images/favicon/Berlin_de_FB_Social.png",deadline:"2026-09-15T14:00:00+02:00",organizer:"Berlin Senate Department for Culture and Social Cohesion",eligibility:"主要居住並工作於柏林的專業藝術家；非歐盟申請者須具可從事自由工作的居留許可；學生與教授不符資格",budget:"依人數、目的地與期間核給 €1,000–€10,000；歐洲內每月參考 €2,500、歐洲外 €3,000"),
  call(n:3,key:"opportunity-2026-berlin-residencies-istanbul-paris-newyork-tokyo",name:"柏林／伊斯坦堡、巴黎、紐約、東京交換駐地",cities:["Berlin","柏林","Istanbul","伊斯坦堡","Paris","巴黎","New York","紐約","Tokyo","東京"],media:["藝術駐地","國際交流","視覺藝術"],work:"2027／2028 指定城市駐地｜截止 2026.09.15 14:00 CEST",comment:"為柏林藝術家提供伊斯坦堡、紐約、東京與巴黎的三至六個月駐地，在合作機構的工作室或工作室公寓中發展新作並連結當地藝術現場。",url:"https://www.berlin.de/sen/kultur/en/funding/funding-programmes/international-cultural-exchange/artikel.236165.en.php",image:"https://www.berlin.de/i9f/r1/images/favicon/Berlin_de_FB_Social.png",deadline:"2026-09-15T14:00:00+02:00",organizer:"Berlin Senate Department for Culture and Social Cohesion（與各城市合作機構）",eligibility:"主要居住並工作於柏林、已具專業實績的指定領域藝術家；不同城市與門類另有資格限制",budget:"東京每月 €3,000 並免工作室公寓租金；巴黎每月 €2,500 並免 Cité 工作室公寓租金；其他城市依官方簡章"),
  call(n:4,key:"opportunity-2026-berlin-film-video-work-grant-2027",name:"柏林／2027 電影與錄像創作獎助",cities:["Berlin","柏林","Germany","德國"],media:["實驗電影","錄像藝術","影像創作"],work:"4–6 個月創作獎助｜截止 2026.10.01 11:00 CEST",comment:"支持居住柏林的女性及跨性別、雙性與非二元電影／錄像創作者進行藝術發展或完成具體影像計畫，讓申請者在有限期間專注創作。",url:"https://www.berlin.de/sen/kultur/en/funding/funding-programmes/funding-for-women-artists/artikel.233303.en.php",image:"https://www.berlin.de/i9f/r1/images/favicon/Berlin_de_FB_Social.png",deadline:"2026-10-01T11:00:00+02:00",organizer:"Berlin Senate Department for Culture and Social Cohesion",eligibility:"主要居住並工作於柏林的女性、跨性別、雙性與非二元電影／錄像創作者；學生、博士生與教授不符資格；錄像裝置計畫不受理",budget:"4、5 或 6 個月，每月 €2,000"),
  call(n:5,key:"opportunity-2026-berlin-visual-art-presentations-2027",name:"柏林／2027 當代視覺藝術呈現補助",cities:["Berlin","柏林","Germany","德國"],media:["視覺藝術","策展計畫","公共呈現"],work:"2027 當代視覺藝術計畫｜截止 2026.10.13 11:00 CEST",comment:"支持柏林藝術家、團體、策展人、計畫空間、區級藝廊與藝術協會提出個展、群展和出版，強調面向公眾的當代視覺藝術呈現。",url:"https://www.berlin.de/sen/kultur/foerderung/foerderprogramme/bildende-kunst/artikel.60223.php",image:"https://www.berlin.de/i9f/r1/images/favicon/Berlin_de_FB_Social.png",deadline:"2026-10-13T11:00:00+02:00",organizer:"Berlin Senate Department for Culture and Social Cohesion",eligibility:"柏林視覺藝術家、藝術團體、策展人、計畫空間／倡議、區級藝廊及藝術協會；學生不符資格，團體多數成員須住柏林",budget:"個人出版最高 €27,000；個人計畫最高 €35,000；群體計畫最高 €55,000")
]

def exhibition(n:, key:, name:, country:, cities:, media:, dates:, url:, image:, type:, edition:, organizer:, curator:, venue:, admission:, comment:, statement:)
  {"category"=>"全球重要展覽","status"=>"官方來源","updated"=>DATE,"id"=>"exhibition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"全球重要展覽","region"=>"全球","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>"#{type}｜#{dates[0]}–#{dates[1]}","comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>statement,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"exhibitionType"=>type,"exhibitionStatus"=>"歷史展覽","startDate"=>dates[0],"endDate"=>dates[1],"edition"=>edition,"organizer"=>organizer,"curator"=>curator,"venue"=>venue,"admission"=>admission,"curatorStatement"=>statement,"curatorStatementSource"=>url,"relatedByCity"=>[]}
end

exhibitions = [
  exhibition(n:1,key:"exhibition-2024-venice-foreigners-everywhere",name:"第 60 屆威尼斯國際藝術展｜Foreigners Everywhere",country:"義大利 / Venice",cities:["Venice","Venezia","威尼斯","Giardini","Arsenale"],media:["國際雙年展","當代藝術","去殖民策展"],dates:["2024-04-20","2024-11-24"],url:"https://www.labiennale.org/en/art/2024/60-esposizione",image:"https://static.labiennale.org/files/styles/full_screen_slide/public/arte/2024/1300x600/pedrosa-ve2.jpg",type:"國際當代藝術雙年展",edition:"第 60 屆",organizer:"La Biennale di Venezia",curator:"Adriano Pedrosa",venue:"Giardini、Arsenale 與威尼斯多處場館",admission:"歷史展覽；當屆官方售票",comment:"主展把外來者、移民、流亡者、離散社群、原住民與酷兒藝術家的位置推到中心，重新審視現代主義美術史長期建立的內外邊界。",statement:"Foreigners Everywhere 同時指向人在異地的處境，也指出每個人內部都存在陌生者；策展以全球南方和被邊緣化的現代主義系譜重寫國際大展的觀看中心。"),
  exhibition(n:2,key:"exhibition-2022-documenta-fifteen",name:"documenta fifteen｜lumbung",country:"德國 / Kassel",cities:["Kassel","卡塞爾","documenta Halle","Fridericianum"],media:["documenta","國際調查展","社會實踐"],dates:["2022-06-18","2022-09-25"],url:"https://documenta.de/en/retrospective/documenta-fifteen",image:"https://documenta.de/media/site/fc7c44c520-1744816169/ops-documenta-identity-press-1-_seite_4-1408x-1-1200x630-crop.png",type:"documenta／國際當代藝術五年展",edition:"第 15 屆",organizer:"documenta und Museum Fridericianum gGmbH",curator:"ruangrupa（藝術總監／策展集體）",venue:"Fridericianum、documenta Halle 與卡塞爾城市場址",admission:"歷史展覽；當屆官方售票",comment:"印尼策展集體 ruangrupa 以 lumbung『共享穀倉』為組織原則，讓藝術家團體共同分配資源、知識與時間，將大型展覽轉化為可持續的協作基礎設施。",statement:"lumbung 強調集體治理、互助與跨地方網絡，不以單一策展論述統一作品，而讓參與者的日常實踐和長期關係構成 documenta。"),
  exhibition(n:3,key:"exhibition-2022-sydney-rivus",name:"第 23 屆雪梨雙年展｜rīvus",country:"澳洲 / Sydney",cities:["Sydney","雪梨","Barangaroo","MCA Australia"],media:["國際雙年展","水文地景","生態藝術"],dates:["2022-03-12","2022-06-13"],url:"https://www.biennaleofsydney.art/biennale-of-sydney-announces-project-highlights-for-the-2022-edition-titled-rivus/",image:"https://www.biennaleofsydney.art/wp-content/uploads/2022/02/Leaf-Work.jpg",type:"國際當代藝術雙年展／水文與生態調查",edition:"第 23 屆",organizer:"Biennale of Sydney",curator:"José Roca 與策展團隊",venue:"Art Gallery of NSW、Barangaroo、MCA Australia 等雪梨場址",admission:"免費",comment:"rīvus 把河流、濕地和其他非人類生命視為展覽參與者，透過藝術、設計與科學合作討論水權、殖民治理和城市水文。",statement:"策展不把自然當作被觀看的背景，而要求人類與河流、植物、動物及祖傳知識建立政治與倫理上的互惠關係。"),
  exhibition(n:4,key:"exhibition-2023-gwangju-soft-weak-water",name:"第 14 屆光州雙年展｜soft and weak like water",country:"韓國 / Gwangju",cities:["Gwangju","光州","Gwangju Biennale Exhibition Hall"],media:["國際雙年展","水系思維","跨文化藝術"],dates:["2023-04-07","2023-07-09"],url:"https://www.gwangjubiennale.org/gb/exhibition/past/14.do",image:"https://www.gwangjubiennale.org/resources/img/upload/BIENNALE/1/5r46b4u155p60hz.jpg",type:"國際當代藝術雙年展",edition:"第 14 屆",organizer:"Gwangju Biennale Foundation",curator:"Sook-Kyung Lee（藝術總監）",venue:"Gwangju Biennale Exhibition Hall 與光州城市場址",admission:"歷史展覽；當屆官方售票",comment:"展覽借用水柔弱卻能改變地形的特質，串聯原住民知識、後殖民記憶、生態危機與跨國遷徙，尋找不依賴支配的共存方式。",statement:"soft and weak like water 將『柔弱』理解為流動、適應和持續作用的力量，以多個地理與時間尺度回應全球危機。"),
  exhibition(n:5,key:"exhibition-2019-aichi-taming-your-passion",name:"愛知三年展 2019｜Taming Y/Our Passion",country:"日本 / Aichi",cities:["Aichi","愛知","Nagoya","名古屋","Toyota","豐田"],media:["國際三年展","藝術與社會","建築場域"],dates:["2019-08-01","2019-10-14"],url:"https://aichitriennale.jp/en/archive/index.html",image:"https://aichitriennale.jp/img/site.png",type:"國際當代藝術三年展",edition:"第 4 屆",organizer:"Aichi Triennale Organizing Committee",curator:"津田大介 Tsuda Daisuke（藝術總監）",venue:"Aichi Arts Center、Nagoya City Art Museum、名古屋與豐田城市場址",admission:"歷史展覽；當屆依官方票務",comment:"展覽以『馴服我們的熱情』追問政治分裂、網路輿論與情感如何塑造公共領域，並在藝術、表演、電影和城市空間間建立多重討論入口。",statement:"策展將熱情視為民主與創作的動力，也視為可能失控的力量；藝術被用來延長對話，而不是快速收束衝突。")
]

def related(item, candidates)
  keys=item.fetch("cityKeywords",[]).map{|x|x.downcase.strip}
  candidates.select{|o|!(keys & o.fetch("cityKeywords",[]).map{|x|x.downcase.strip}).empty?}.map{|o|o["id"]}.uniq
end

comp_path=File.join(DATA,"competitions.json"); comp=JSON.parse(File.read(comp_path))
expired_path=File.join(DATA,"expired-20260908.json")
previous_expired=Dir[File.join(DATA,"expired-*.json")].reject{|p|p==expired_path}.flat_map{|p|JSON.parse(File.read(p)).fetch("entries",[])}
existing_expired=File.exist?(expired_path) ? JSON.parse(File.read(expired_path)).fetch("entries",[]) : []
today_expired=comp["entries"].select{|e|e["deadline"] && DateTime.parse(e["deadline"])<=NOW}
archive=(previous_expired+existing_expired+today_expired).uniq{|e|e["dedupeKey"]||e["id"]}
old_keys=previous_expired.map{|e|e["dedupeKey"]||e["id"]}.uniq
removed=archive.count{|e|!old_keys.include?(e["dedupeKey"]||e["id"])}
comp["entries"].reject!{|e|today_expired.include?(e)||e["updated"]==DATE}
existing_keys=comp["entries"].map{|e|e["dedupeKey"]}; calls.each{|e|comp["entries"]<<e unless existing_keys.include?(e["dedupeKey"])}

all_art_files=Dir[File.join(DATA,"backfill-{july,august,september}-*.json")].reject{|p|p.end_with?("manifest.json")||p.end_with?("20260908.json")}
all_art=all_art_files.flat_map{|p|v=JSON.parse(File.read(p));v.is_a?(Hash)?v.fetch("entries",[]):v}+arts
arts.each{|e|e["relatedByCity"]=related(e,comp["entries"])}
comp["entries"].each{|e|e["relatedByCity"]=related(e,all_art)}

daily={"meta"=>{"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"total"=>20,"dynamicEntries"=>10,"globalClassicEntries"=>5,"germanClassicEntries"=>5,"source"=>"KÖR Wien、Museum der 1000 Orte 官方頁","selectionPolicy"=>"優先地景、生態、參與、聲光、動態、數位與建築整合作品；不以傳統人物、胸像、騎馬像或基座式紀念碑湊數。","note"=>"9/8 固定 10＋5＋5；另有德國公開徵選 5 則與全球重要展覽 5 篇。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"checkedUniqueSources"=>20,"brokenOrBlockedReplaced"=>0,"rule"=>"實際瀏覽器逐頁開啟"},"imageAudit"=>{"checkedAt"=>GENERATED_AT,"imageEntries"=>20,"missing"=>0,"rule"=>"官方圖片逐一載入驗證"}},"entries"=>arts}
comp["meta"]={"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"source"=>"官方主辦機構徵件頁","activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"note"=>"9/8 新增 5 筆有效德國公開徵選；移除 #{removed} 筆逾期案件。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"missingCityKeywords"=>0,"uniqueNewSourcesChecked"=>5,"blockedSourceReplaced"=>0}}

ex_path=File.join(DATA,"exhibitions.json"); ex=JSON.parse(File.read(ex_path)); ex["entries"].reject!{|e|e["updated"]==DATE}
ex_keys=ex["entries"].map{|e|e["dedupeKey"]}; exhibitions.each{|e|ex["entries"]<<e unless ex_keys.include?(e["dedupeKey"])}
ex["meta"]={"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"9/8 新增 5 篇全球重要展覽；全部使用官方來源與可載入圖片。"}

File.write(File.join(DATA,"backfill-september-20260908.json"),JSON.pretty_generate(daily)+"\n")
File.write(comp_path,JSON.pretty_generate(comp)+"\n");File.write(ex_path,JSON.pretty_generate(ex)+"\n")
sept_path=File.join(DATA,"backfill-september-manifest.json");sept=JSON.parse(File.read(sept_path));files=(sept.fetch("files",[])+["backfill-september-20260908.json"]).uniq.sort
sept.merge!({"version"=>"2026-09-08-public-art-r64","generatedAt"=>GENERATED_AT,"files"=>files,"expectedEntries"=>files.length*20,"statementEntries"=>files.length*20,"statementSourceEntries"=>files.length*20,"statementBacklog"=>0,"imageEntries"=>files.length*20,"imageBacklog"=>0,"note"=>"截至 2026-09-08 累計 #{files.length*20} 則；今日新增 20 則公共藝術（10／5／5），已套用非傳統紀念碑選材規則。"});File.write(sept_path,JSON.pretty_generate(sept)+"\n")
cm_path=File.join(DATA,"competition-manifest.json");cm=JSON.parse(File.read(cm_path));cm.merge!({"version"=>"2026-09-08-competition-r40","generatedAt"=>GENERATED_AT,"activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"deadlineTimezoneEntries"=>comp["entries"].count{|e|e["deadlineTimezone"]},"deadlinePrecisionEntries"=>comp["entries"].count{|e|e["deadlinePrecision"]},"cityKeywordEntries"=>comp["entries"].count{|e|!e.fetch("cityKeywords",[]).empty?},"note"=>"2026-09-08 新增 5 則德國公開徵選並移除 #{removed} 則逾期案件。"});File.write(cm_path,JSON.pretty_generate(cm)+"\n")
em_path=File.join(DATA,"exhibition-manifest.json");em=JSON.parse(File.read(em_path));em.merge!({"version"=>"2026-09-08-global-exhibitions-r10","generatedAt"=>GENERATED_AT,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"2026-09-08 新增 5 篇全球重要展覽；全部使用官方來源與可顯示圖片。"});File.write(em_path,JSON.pretty_generate(em)+"\n")
File.write(expired_path,JSON.pretty_generate({"archivedAt"=>GENERATED_AT,"removedToday"=>removed,"entries"=>archive})+"\n")
index_path=File.join(ROOT,"index.html");index=File.read(index_path).gsub("20260907-daily-r63","20260908-daily-r64");File.write(index_path,index)
File.write(File.join(DATA,"deploy-touch.txt"),"2026-09-08 daily r63 — 20 public artworks + 5 active German open calls + 5 global exhibitions; #{removed} expired calls removed.\n")
puts JSON.pretty_generate({date:DATE,public_art:arts.length,dynamic:10,global_classics:5,german_classics:5,calls:calls.length,exhibitions:exhibitions.length,expired_removed:removed})
