require "json"
require "date"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "data")
DATE = "2026-09-05"
GENERATED_AT = "2026-09-05T01:30:00+08:00"
NOW = DateTime.parse(GENERATED_AT)

def art(id:, key:, name:, tier:, country:, cities:, media:, work:, comment:, url:, image:)
  {"category"=>"作品/展覽","status"=>"官方來源","updated"=>DATE,"id"=>id,"dedupeKey"=>key,"name"=>name,"tier"=>tier,"region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>work,"classicImage"=>image,"classicDesc"=>comment,"relatedByCity"=>[]}
end

arts_data = [
  ["current","moser-wagner-veza-visite","Gertrude Moser-Wagner｜Veza Visite","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["多媒體","行為藝術","文學記憶"],"Veza Visite｜2024","以 Veza Canetti 的生命與文字為入口，透過拜訪、朗讀和多媒體行動，讓被文學史遮蔽的女性作者重新進入城市記憶。","https://www.koer.or.at/projects/veza-visite/","https://www.koer.or.at/site/assets/files/13891/kaja_ewa-1-47_kleiner.500x0.jpg"],
  ["current","bik-van-der-pol-school-walking","Bik Van der Pol｜School of Walking","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["城市步行","社會參與","生態研究"],"School of Walking｜2024","與 urbanize! 以步行作為共同研究，從日常路線討論能源轉型、社會關係與城市如何被身體重新理解。","https://www.koer.or.at/projects/school-of-walking/","https://www.koer.or.at/site/assets/files/13884/urb24_collage_nl_kopie.500x0.jpg"],
  ["current","hybrid-dessous-wiener-bade-linie","Hybrid Dessous｜Wiener Bade Linie","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Donaukanal"],["時尚設計","水域文化","社會介入"],"Wiener Bade Linie｜2024","以混合泳裝回應多瑙河運河的游泳者和城市規範，把衣著、身體自由與公共水域的可使用性放在同一條岸線討論。","https://www.koer.or.at/projects/wiener-bade-linie/","https://www.koer.or.at/site/assets/files/13812/nl_sa_1.500x0.jpg"],
  ["current","bankleer-umwoelkt","bankleer｜Umwölkt","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["公共介入","裝置","政治藝術"],"Umwölkt／Beclouded｜2024","在多重危機的陰影下，以跨媒介公共介入製造感知上的雲層，促使觀眾辨認政治語言、日常焦慮與共同行動的交會。","https://www.koer.or.at/projects/umwoelkt/","https://www.koer.or.at/site/assets/files/13926/markus_krottendorfer_dsc2317_kleinst.500x0.jpg"],
  ["current","palomia-silverpiece-reloaded","PALOMIA｜Silverpiece Reloaded","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["壁畫","跨世代共創","街頭藝術"],"Silverpiece Reloaded｜2024","長者與青年共同發展街頭壁畫，把通常被年齡分隔的經驗放在同一面牆上，讓公共藝術成為跨世代協作的可見證據。","https://www.koer.or.at/projects/silverpiece-reloaded/","https://www.koer.or.at/site/assets/files/13835/07.500x0.jpg"],
  ["current","infoscreen-20-seconds-art-2024","20 seconds for art｜2024 五件得獎短片","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Austria"],["錄像藝術","公共螢幕","短片"],"20 seconds for art 2024｜Community 3.0","從一百六十四件投稿選出五部二十秒短片，在奧地利大眾運輸螢幕播放，以極短影像測試公共注意力與新型共同體。","https://www.koer.or.at/projects/five-award-winning-short-films-20-seconds-for-art-2024/","https://www.koer.or.at/site/assets/files/13761/20seconds_logo_subline-1_verkuerzt.500x0.jpg"],
  ["current","see-ua-connecting-landscapes","Reinhold Zisser／Mohrytsia｜SEE UA – Connecting Landscapes","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Seestadt","Mohrytsia"],["地景藝術","駐地","跨國合作"],"SEE UA – Connecting Landscapes｜2024","把烏克蘭 Mohrytsia 地景藝術研討會帶到 Seestadt，從流離、家園和地景之間建立跨國連線，讓遷徙經驗在公共空間被共同承接。","https://www.koer.or.at/projects/see-ua-connecting-landscapes/","https://www.koer.or.at/site/assets/files/13432/img_5215.500x0.jpg"],
  ["current","theresa-schuetz-touch-ground","Theresa Schütz｜Touch Ground","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["行為藝術","城市步行","土地政治"],"Touch Ground｜2024","以表演性城市旅程追問土壤、公共利益、所有權與邊界，讓腳下看似沉默的地面顯露法律和歷史的分配關係。","https://www.koer.or.at/projects/touch-ground/","https://www.koer.or.at/site/assets/files/12348/kleiner_img_3712.500x0.jpg"],
  ["current","nazarpour-hair-stones-voices","Shahrzad Nazarpour｜Hair, Stones and Voices","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["行為藝術","身體政治","聲音"],"Hair, Stones and Voices｜2024","系列演出把頭髮化為抵抗、自由與記憶的媒介，讓身體在公共場域中說出被制度壓抑的聲音。","https://www.koer.or.at/projects/hair-stones-and-voices/","https://www.koer.or.at/site/assets/files/12895/kleiner_4_c_mq_thomas_meyer_4.500x0.jpg"],
  ["current","vlaschits-herbarium-burggasse","Marianne Vlaschits｜Herbarium Burggasse","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Burggasse"],["壁畫","植物圖像","捷運藝術"],"Herbarium Burggasse｜2024","在 U6 樓梯空間建立可穿行的繪畫植物誌，以想像性花草改變轉乘中的視線，讓基礎設施暫時成為感官花園。","https://www.koer.or.at/projects/herbarium-burggasse/","https://www.koer.or.at/site/assets/files/13166/2024_06_12_marianne-vlaschits_00025_web.500x0.jpg"],
  ["classic-global","ward-seventh-regiment","John Quincy Adams Ward／Richard Morris Hunt｜7th Regiment Memorial","經典檔案庫","美國 / New York City",["New York City","紐約市","Central Park","中央公園"],["青銅雕塑","軍事紀念","紀念碑"],"7th Regiment Memorial｜1874","以普通市民士兵而非勝利姿態紀念內戰犧牲者，簡潔站姿和建築基座把個人哀悼放入公園的公共歷史。","https://www.centralparknyc.org/locations/7th-regiment-memorial","https://d2wsrtli9cxkek.cloudfront.net/media/images/7th-Regiment-Memorial_20190515_006.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=1151.1627906977&q=80&w=2475&s=70b90ec2b4e38dc84aff810d5cad3a80"],
  ["classic-global","daumas-jose-san-martin","Louis-Joseph Daumas｜José de San Martín","經典檔案庫","美國 / New York City",["New York City","紐約市","Central Park","中央公園"],["騎馬像","青銅","國際紀念"],"José de San Martín｜1862 原作／1951 紐約設置","布宜諾斯艾利斯騎馬紀念像的複製品在紐約落地，將南美獨立史和城市移民共同體的紀念需求連結起來。","https://www.centralparknyc.org/locations/jose-de-san-martin","https://d2wsrtli9cxkek.cloudfront.net/media/images/locations/San-Martin-DSC_0390.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=1151.1627906977&q=80&w=2475&s=a3c69efc111327953382dd3cf758c94e"],
  ["classic-global","piccirilli-manship-hutchins-bench","Piccirilli Brothers／Paul Manship｜Waldo Hutchins Bench","經典檔案庫","美國 / New York City",["New York City","紐約市","Central Park","中央公園"],["花崗岩","日晷","紀念座椅"],"Waldo Hutchins Bench｜1932","二十七英尺長的紀念座椅把休息、日晷和銘文整合為可使用的公共作品，使時間測量與日常停留共存。","https://www.centralparknyc.org/locations/waldo-hutchins-bench","https://d2wsrtli9cxkek.cloudfront.net/media/images/locations/Waldo-Hutchins-Bench_20181127_0001.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=1151.1627906977&q=80&w=2475&s=096260b69e42a0ac7ee880853a157dea"],
  ["classic-global","cain-tigress-cubs","Auguste Nicholas Cain｜Tigress and Cubs","經典檔案庫","美國 / New York City",["New York City","紐約市","Central Park","中央公園","Central Park Zoo"],["動物雕塑","青銅","自然主義"],"Tigress and Cubs｜1867","母虎、兩隻幼虎與獵物孔雀構成緊繃敘事，反映十九世紀動物雕塑如何把野性、母性和自然觀置入城市公園。","https://www.centralparknyc.org/locations/tigress-and-cubs","https://d2wsrtli9cxkek.cloudfront.net/media/images/locations/Central-Park-Zoo_20190307_103.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=1151.1627906977&q=80&w=2475&s=d7b64ae5853638e11a91aa5d9c4bbffa"],
  ["classic-global","kemeys-still-hunt","Edward Kemeys｜Still Hunt","經典檔案庫","美國 / New York City",["New York City","紐約市","Central Park","中央公園"],["動物雕塑","青銅","場域特定"],"Still Hunt｜1881／1883 設置","伏在岩石上的美洲豹以地形作為作品的一部分，將觀看者置於獵物位置，是公共雕塑與自然場址高度整合的早期案例。","https://www.centralparknyc.org/locations/still-hunt","https://d2wsrtli9cxkek.cloudfront.net/media/images/ff-wide@3x-Still-Hunt.jpg?auto=compress%2Cformat&crop=focalpoint&fit=crop&fp-x=0.5&fp-y=0.5&h=1151.1627906977&q=80&w=2475&s=30a9d40e2f9b41320895995fed0bcc78"],
  ["classic-german","klingelhoeller-ich-bin-hier","Harald Klingelhöller｜Ich bin hier, Du bist hier","經典檔案庫","德國 / Berlin",["Berlin","柏林","Werderscher Markt"],["文字雕塑","建築整合","裝置"],"Ich bin hier, Du bist hier｜2001","在外交部建築中以文字與物件標記彼此的位置，使行政空間中的身分、對話與觀看關係成為作品本身。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/ich-bin-hier-du-bist-hier","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/6ffe3269cc475af99578392fe195e932fe61d737.jpg"],
  ["classic-german","mangold-untitled-wall","Julia Mangold｜o. T. (Wandarbeit)","經典檔案庫","德國 / Berlin",["Berlin","柏林","Marie-Elisabeth-Lüders-Haus"],["牆面藝術","鋼材","建築整合"],"o. T. (Wandarbeit)｜2003","冷冽鋼板與牆面尺度相互咬合，把材料重量、表面反光和國會建築的秩序轉成安靜但持續的空間張力。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/o-t-wandarbeit-1","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/09ef7acaf77d8f3d08bf39a2085a8edadb486861.jpg"],
  ["classic-german","hauser-flaechenwand","Erich Hauser｜Flächenwand","經典檔案庫","德國 / Berlin",["Berlin","柏林","Staatsbibliothek"],["壓克力繪畫","牆面藝術","抽象"],"Flächenwand｜1977","十三公尺長、六公尺高的黑白線性牆面介入圖書館門廳，以近乎書寫的抽象節奏回應知識建築與人流。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/flachenwand","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/7c80c673530af26e1db2c685c3cca6004ff70a87.jpg"],
  ["classic-german","goetze-untitled-2001","Moritz Götze｜o. T.","經典檔案庫","德國 / Berlin",["Berlin","柏林","Bundesministerium für Wirtschaft"],["琺瑯","壁畫","敘事圖像"],"o. T.｜2001","以鮮明琺瑯圖像包覆部會餐廳牆面，將窗洞和自然場景納入構圖，使日常用餐空間形成近似漫畫的公共敘事。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/o-t-9","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/c01700ebb0fdaa0a31c14f21be327ceda8b576a6.jpg"],
  ["classic-german","gomez-spiegel-ornaments-social-living","Francisca Gómez／Alexandra Spiegel｜Ornaments of Social Living","經典檔案庫","德國 / Berlin",["Berlin","柏林","BMAS"],["燈箱","攝影裝置","社會空間"],"Ornaments of Social Living｜2020","六處休息和等候區以不同尺度燈箱組成社會生活的裝飾語彙，讓行政建築的過渡空間承載人的姿態與關係。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/ornaments-of-social-living","https://www.museum-der-1000-orte.de/media/cache/resolve/zoom/images/a9471368c351280cb51a7c2d3d8849e2a5dce10c.jpg"]
]

arts = arts_data.each_with_index.map do |a,i|
  group,key,title,tier,country,cities,media,work,comment,url,image=a
  n=group=="current" ? i+1 : group=="classic-global" ? i-9 : i-14
  art(id:"#{group}-#{DATE}-#{format('%02d',n)}",key:"art-#{DATE}-#{key}",name:"#{format('%02d',n)}｜#{title}",tier:tier,country:country,cities:cities,media:media,work:work,comment:comment,url:url,image:image)
end

def call(n,key,name,cities,media,work,comment,url,image,deadline,organizer,eligibility,budget,fee)
  {"category"=>"公開徵件","status"=>"官方來源","updated"=>DATE,"id"=>"competition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"競圖資料庫","region"=>"西方","country"=>"德國 / #{cities.first}","cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"deadline"=>deadline,"deadlineLabel"=>work.split("截止 ").last,"deadlineTimezone"=>"Europe/Berlin","deadlinePrecision"=>"time","organizer"=>organizer,"eligibility"=>eligibility,"budget"=>budget,"applicationFee"=>fee,"relatedByCity"=>[]}
end

calls = [
  call(1,"opportunity-2027-goldrausch-professional-program","Berlin｜Goldrausch 2027 藝術家專業培力公開徵選",["Berlin","柏林"],["專業培力","視覺藝術","FLINTA"],"十二個月藝術職涯培力｜截止 2026.09.15 23:59 CEST","一年期課程提供作品呈現、藝術市場、稅務、財務、網站與出版實作，並以年終群展提升十五位藝術家的能見度。","https://goldrausch.org/","https://goldrausch.org/wp-content/themes/goldrausch-theme/assets/img/header-default-img.png","2026-09-15T23:59:59+02:00","Goldrausch Frauennetzwerk Berlin e. V.","居住柏林的 FLINTA 視覺藝術家；不限年齡，具專業實踐、德英語討論能力與全年投入時間","十五個免費培力名額；課程成本由 ESF Plus 與柏林州資助，無生活津貼","免費"),
  call(2,"opportunity-2027-enzymkultur-video-paths","Essen｜Videokunst 2027：Pfade, Wege, Straßen",["Essen","埃森"],["錄像藝術","實驗電影","公開放映"],"二十分鐘內錄像公開徵件｜截止 2026.09.30 23:59 CEST","徵集實驗、紀錄、敘事或自由形式錄像，入選作品將在車庫、花園與地下室等日常場景組成策展放映。","https://enzymkultur.de/news/90-open-call-videokunst-2027-pfade%2C-wege%2C-stra%C3%9Fen","https://enzymkultur.de/images/enzymkultur/pfade_wege/projekt/strassen%20wege%20s.png","2026-09-30T23:59:59+02:00","EnzymKultur e. V.","各國錄像藝術家；作品最長約 20 分鐘、mp4，每人至多 3 件，非德語作品須附字幕","預計每位參與者最高 €100 放映費，視補助核定而定","免費"),
  call(3,"opportunity-2026-arsliturgica-wen-suchst-du","Nordwalde｜arsLITURGICA：Wen suchst du?",["Nordwalde","諾德瓦爾德","Münster"],["宗教空間","場域特定","公共藝術"],"St. Dionysius 教堂回應空間設計｜截止 2026.11.17 18:00 CET","為教堂入口創作當代藝術介入，以抹大拉的馬利亞為思想起點，回應參與、召命、宣告與責任。","https://dli.institute/wp/news/ars-liturgica-wettbewerb-2026-wen-suchst-du/","https://dli.institute/wp/wp-content/themes/dli/img/liturgie_de_titel.jpg","2026-11-17T18:00:00+01:00","Initiative arsLITURGICA","依官方競賽文件申請的專業藝術家或設計團隊；方案需適用 St. Dionysius 教堂入口","一等獎 €5,000、二等獎 €3,000、三等獎 €1,000","免費"),
  call(4,"opportunity-2028-senefelder-award-14","Offenbach｜第 14 屆 Senefelder Award 2028",["Offenbach am Main","奧芬巴赫"],["石版畫","平版印刷","藝術獎"],"國際原創平版藝術徵件｜截止 2027.03.12 23:59 CET","表揚石版和平版藝術的技術與創新；第一階段數位匿名評選，入圍者再寄送原作並納入基金會收藏。","https://www.senefelderstiftung.com/de/senefelder-award-2028/","https://image.jimcdn.com/app/cms/image/transf/dimension=1030x10000:format=jpg/path/s2e9ec10d62fe7737/image/i090c5befa5e8dc43/version/1492724206/image.jpg","2027-03-12T23:59:59+01:00","Internationale Senefelder-Stiftung／BBK","全球藝術家；提交 2023 年後完成的石版、平版或實驗混合平版原作，最大 100 × 70 公分","總獎金 €2,000；入選作品預計 2028 年於 Klingspor Museum 展出","免費"),
  call(5,"opportunity-2026-ostallgaeu-art-exhibition-48","Marktoberdorf｜第 48 屆 Ostallgäuer Kunstausstellung",["Marktoberdorf","馬克特奧伯多夫","Bayerisch Schwaben"],["區域藝術展","當代藝術","藝術獎"],"Künstlerhaus Marktoberdorf 區域藝術徵選｜截止 2026.09.17 23:59 CEST","年度評選展聚焦 Bayerisch Schwaben 當代創作及其與 Künstlerhaus 建築的場域關係，並由評審選出三項獎項。","https://www.marktoberdorf.de/mitteilung/ausschreibung_6661","https://www.marktoberdorf.de/static/img/layout/logo-mod.png","2026-09-17T23:59:59+02:00","Stadt Marktoberdorf／Künstlerhaus Marktoberdorf","在 Bayerisch Schwaben 生活或工作的藝術家，依 2026 官方申請表與展覽規章送件","Johann-Georg-Fischer-Kunstpreis €3,000；Franz Schmid Stiftung €2,500；Familie Paul Breitkopf €2,000","依官方公告未列申請費，視為免費")
]

def exhibition(n,key,name,country,cities,media,dates,url,image,type,status,edition,organizer,curator,venue,admission,comment,statement)
  {"category"=>"國際展覽","status"=>"官方來源","updated"=>DATE,"id"=>"exhibition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"全球重要展覽","region"=>"全球","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>"#{name}｜#{dates[0]}–#{dates[1]}","comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"exhibitionType"=>type,"exhibitionStatus"=>status,"startDate"=>dates[0],"endDate"=>dates[1],"edition"=>edition,"organizer"=>organizer,"curator"=>curator,"venue"=>venue,"admission"=>admission,"curatorStatement"=>statement,"curatorStatementSource"=>url}
end

exhibitions = [
  exhibition(1,"exhibition-2026-fotofest-global-visions-40","FotoFest Biennial 2026｜Global Visions – FotoFest at 40","美國 / Houston",["Houston","休士頓","Sawyer Yards"],["攝影雙年展","新媒體","國際調查展"],["2026-03-07","2026-05-10"],"https://fotofest.org/biennial-2026","https://fotofest.org/wp-content/uploads/2025/06/FF26–Press-Release.jpeg","國際攝影與新媒體雙年展","已結束／檔案","第 21 屆／40 週年","FotoFest","Wendy Watriss、Steven Evans；共同策展 Annick Dekiouk、Madi Murphy","Sawyer Yards Galleries 及休士頓城市合作場址","依官方場館資訊","四十週年版本回望一九八六至二〇二四的二十屆歷史，以四百五十多位、來自五十八國的藝術家重構地理、身分、戰爭、生態與社會變遷。","策展不把回顧做成封閉年表，而以歷屆核心作品重組全球視野，檢驗攝影如何持續改變公共記憶與國際交流。"),
  exhibition(2,"exhibition-2025-chicago-architecture-shift","Chicago Architecture Biennial 2025｜SHIFT","美國 / Chicago",["Chicago","芝加哥","Chicago Cultural Center"],["建築雙年展","城市研究","公共設計"],["2025-09-19","2026-02-28"],"https://chicagoarchitecturebiennial.org/shift-architecture-in-times-of-radical-change-participant-announcement/","https://cab-1.storage.googleapis.com/wp-content/uploads/2023/08/16094156/shift_web_banner_02_1920x760-1024x405.png","國際建築與都市設計雙年展","已結束／檔案","第 6 屆／10 週年","Chicago Architecture Biennial／DCASE","Florencia Rodriguez","Chicago Cultural Center 及芝加哥都會區多處場址","全系列免費向公眾開放","百餘組建築師、設計者和創意實踐者以住房、生態、材料與公共制度回應激烈變動中的城市，將建築視為可共同使用的工具。","SHIFT 主張建築必須理解並回應政治、氣候、科技和文化轉變，以集體、實驗且貼近日常的方法想像可行的未來。"),
  exhibition(3,"exhibition-2025-seoul-mediacity-seance","第 13 屆首爾媒體城市雙年展｜Séance: Technology of the Spirit","韓國 / Seoul",["Seoul","首爾","Seoul Museum of Art","NAKWON SANGGA"],["媒體藝術雙年展","錄像","裝置","電影"],["2025-08-26","2025-11-23"],"https://mediacityseoul.kr/en/yesterday/projects/2025","https://mediacityseoul.kr/media/pages/yesterday/projects/2025/0eb73edc73-1756199725/smb13-01-1000x.jpg","國際媒體藝術雙年展","已結束／檔案","第 13 屆","Seoul Museum of Art","Anton Vidokle、Hallie Ayres、Lukas Brasiskis","Seoul Museum of Art、NAKWON SANGGA、Cinematheque Seoul Art Cinema","依首爾市立美術館官方資訊","四十九組藝術家以約六十件錄像、裝置與電影追索神祕、靈視和被壓抑的知識傳統，反思現代理性體系如何塑造感知。","策展把雙年展理解成一場降神會：藝術不是裝飾性的靈性符號，而是面對政治與社會不安時擴張知覺、重新組織世界意義的方法。"),
  exhibition(4,"exhibition-2025-seoul-architecture-radically-human","第 5 屆首爾建築與都市雙年展｜Radically More Human","韓國 / Seoul",["Seoul","首爾","Songhyeon Green Plaza"],["建築雙年展","公共空間","城市設計"],["2025-09-26","2025-11-18"],"https://seoulbiennale.org/front/eng/about/biennaleinfo.do","https://seoulbiennale.org/upload/seditorMulti/2025090911333873926999-5282-4f1a-ab1f-5bc3a86d38e5.jpg","國際建築與都市雙年展","已結束／檔案","第 5 屆","Seoul Metropolitan Government","總監 Thomas Heatherwick；城市展策展 Keehyun Ahn 等","Songhyeon Green Plaza、Seoul Hall of Urbanism & Architecture 周邊","依官方場址資訊","以更有人性為總題，從情感、可愛與可長久維護的建築出發，讓市民而非專家單獨決定城市應如何被感受與使用。","Thomas Heatherwick 將真正的永續連結到人們是否愛一個地方；雙年展因而把建築品質轉成所有市民都能發言的公共問題。"),
  exhibition(5,"exhibition-2023-liverpool-umoya","Liverpool Biennial 2023｜uMoya: The Sacred Return of Lost Things","英國 / Liverpool",["Liverpool","利物浦","Cotton Exchange","Tobacco Warehouse"],["國際雙年展","公共藝術","表演","跨媒介"],["2023-06-10","2023-09-17"],"https://www.biennial.com/previous-biennials/","https://archive.biennial.com/img/a61dd738bd5f79cf/lb2023-website-988x248.jpg","國際當代藝術雙年展","已結束／檔案","第 12 屆","Liverpool Biennial","Khanyisile Mbongwa；Samantha Lackey 與團隊","Tate Liverpool、Bluecoat、FACT、Cotton Exchange、Tobacco Warehouse 與戶外場址","免費","uMoya 在 isiZulu 中同時指精神、呼吸、空氣、氣候和風，三十多組藝術家藉祖先與原住民知識回應殖民造成的持續失落。","策展以 uMoya 作為羅盤與通道，讓物件和人跨地移動時攜帶的力量重新顯影，並從災難史轉向療癒與堅持活著的公共實踐。")
]

def related(item,candidates)
  keys=item.fetch("cityKeywords",[]).map{|x|x.downcase.strip}
  candidates.select{|o|!(keys & o.fetch("cityKeywords",[]).map{|x|x.downcase.strip}).empty?}.map{|o|o["id"]}.uniq
end

comp_path=File.join(DATA,"competitions.json")
comp=JSON.parse(File.read(comp_path))
expired_path=File.join(DATA,"expired-20260905.json")
previous_expired=Dir[File.join(DATA,"expired-*.json")].reject{|p|p==expired_path}.flat_map{|p|JSON.parse(File.read(p)).fetch("entries",[])}
existing_expired=File.exist?(expired_path) ? JSON.parse(File.read(expired_path)).fetch("entries",[]) : []
today_expired=comp["entries"].select{|e|e["deadline"] && DateTime.parse(e["deadline"])<=NOW}
archive=(previous_expired+existing_expired+today_expired).uniq{|e|e["dedupeKey"]||e["id"]}
old_keys=previous_expired.map{|e|e["dedupeKey"]||e["id"]}.uniq
removed=archive.count{|e|!old_keys.include?(e["dedupeKey"]||e["id"])}
comp["entries"].reject!{|e|today_expired.include?(e)||e["updated"]==DATE}
existing_keys=comp["entries"].map{|e|e["dedupeKey"]}
calls.each{|e|comp["entries"]<<e unless existing_keys.include?(e["dedupeKey"])}

all_art_files=Dir[File.join(DATA,"backfill-{july,august,september}-*.json")].reject{|p|p.end_with?("manifest.json")||p.end_with?("20260905.json")}
all_art=all_art_files.flat_map{|p|v=JSON.parse(File.read(p));v.is_a?(Hash) ? v.fetch("entries",[]) : v}+arts
arts.each{|e|e["relatedByCity"]=related(e,comp["entries"])}
comp["entries"].each{|e|e["relatedByCity"]=related(e,all_art)}

daily={"meta"=>{"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"total"=>20,"dynamicEntries"=>10,"globalClassicEntries"=>5,"germanClassicEntries"=>5,"source"=>"KÖR Wien、Central Park Conservancy、Museum der 1000 Orte 官方頁","note"=>"9/5 固定 10＋5＋5；另有德國公開徵選 5 則與全球重要展覽 5 篇。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"checkedUniqueSources"=>20,"brokenOrBlockedReplaced"=>0,"rule"=>"實際瀏覽器逐頁檢查"},"imageAudit"=>{"checkedAt"=>GENERATED_AT,"imageEntries"=>20,"missing"=>0,"rule"=>"官方直接圖片逐一載入驗證"}},"entries"=>arts}
comp["meta"]={"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"source"=>"官方主辦機構徵件頁","activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"note"=>"9/5 新增 5 筆有效德國公開徵選；移除 #{removed} 筆逾期案件。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"missingCityKeywords"=>0,"uniqueNewSourcesChecked"=>5,"blockedSourceReplaced"=>0}}

ex_path=File.join(DATA,"exhibitions.json")
ex=JSON.parse(File.read(ex_path));ex["entries"].reject!{|e|e["updated"]==DATE}
ex_keys=ex["entries"].map{|e|e["dedupeKey"]};exhibitions.each{|e|ex["entries"]<<e unless ex_keys.include?(e["dedupeKey"])}
ex["meta"]={"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"9/5 新增 5 篇全球重要展覽；全部使用可開啟官方來源與可載入圖片。"}

File.write(File.join(DATA,"backfill-september-20260905.json"),JSON.pretty_generate(daily)+"\n")
File.write(comp_path,JSON.pretty_generate(comp)+"\n")
File.write(ex_path,JSON.pretty_generate(ex)+"\n")

sept_path=File.join(DATA,"backfill-september-manifest.json");sept=JSON.parse(File.read(sept_path));files=(sept.fetch("files",[])+["backfill-september-20260905.json"]).uniq.sort
sept.merge!({"version"=>"2026-09-05-public-art-r59","generatedAt"=>GENERATED_AT,"files"=>files,"expectedEntries"=>files.length*20,"statementEntries"=>files.length*20,"statementSourceEntries"=>files.length*20,"statementBacklog"=>0,"imageEntries"=>files.length*20,"imageBacklog"=>0,"note"=>"截至 2026-09-05 累計 #{files.length*20} 則；今日新增 20 則公共藝術（10／5／5）。"});File.write(sept_path,JSON.pretty_generate(sept)+"\n")
cm_path=File.join(DATA,"competition-manifest.json");cm=JSON.parse(File.read(cm_path));cm.merge!({"version"=>"2026-09-05-competition-r36","generatedAt"=>GENERATED_AT,"activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>5,"expiredRemoved"=>removed,"deadlineTimezoneEntries"=>comp["entries"].count{|e|e["deadlineTimezone"]},"deadlinePrecisionEntries"=>comp["entries"].count{|e|e["deadlinePrecision"]},"cityKeywordEntries"=>comp["entries"].count{|e|!e.fetch("cityKeywords",[]).empty?},"note"=>"2026-09-05 新增 5 則德國公開徵選並移除 #{removed} 則今日逾期案件。"});File.write(cm_path,JSON.pretty_generate(cm)+"\n")
em_path=File.join(DATA,"exhibition-manifest.json");em=JSON.parse(File.read(em_path));em.merge!({"version"=>"2026-09-05-global-exhibitions-r7","generatedAt"=>GENERATED_AT,"dailyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"2026-09-05 新增 5 篇全球重要展覽；全部使用官方來源與可顯示圖片。"});File.write(em_path,JSON.pretty_generate(em)+"\n")
File.write(expired_path,JSON.pretty_generate({"archivedAt"=>GENERATED_AT,"removedToday"=>removed,"entries"=>archive})+"\n")
File.write(File.join(DATA,"deploy-touch.txt"),"2026-09-05 daily r59 — 20 public artworks + 5 active German open calls + 5 global exhibitions; 30 source pages and images verified; #{removed} expired calls removed.\n")
