# encoding: UTF-8
require "json"
require "date"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "data")
DATE = "2026-09-13"
GENERATED_AT = "2026-09-13T04:00:00+08:00"
NOW = DateTime.parse(GENERATED_AT)

def art(id:, key:, name:, tier:, country:, cities:, media:, work:, comment:, url:, image:)
  {"category"=>"作品/展覽","status"=>"官方來源","updated"=>DATE,"id"=>id,"dedupeKey"=>key,"name"=>name,"tier"=>tier,"region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>work,"classicImage"=>image,"classicDesc"=>comment,"relatedByCity"=>[]}
end

koer = "https://www.koer.or.at"
art_rows = [
  ["current","koer-curators-stockholm-2025","KÖR Wien｜斯德哥爾摩策展駐留","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Stockholm","斯德哥爾摩"],["策展研究","公共藝術","國際交流"],"Curators in Residence Stockholm｜2025","維也納公共藝術機構以策展駐留交換城市知識，將斯德哥爾摩的公共空間治理、委託制度與在地網絡帶回維也納討論。","#{koer}/projects/koer-wien-curators-in-residence-program-in-stockholm/","#{koer}/site/assets/files/14062/grafik_ankuendigung.500x0.jpg"],
  ["current","koer-curators-chisinau-new-york-2024","KÖR Wien｜基希訥烏與紐約策展駐留","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Chisinau","基希訥烏","New York","紐約"],["策展研究","國際交流","城市網絡"],"Curators in Residence Chisinau／New York｜2024","策展人透過兩座政治與文化條件差異極大的城市交換公共藝術方法，使跨國關係成為研究地方制度與藝術生態的工作場域。","#{koer}/projects/koer-vienna-curators-in-residence-programme/","#{koer}/site/assets/files/12431/curators_in_residence-programm_ny_oder_chisinau_c_bmeia.500x0.jpg"],
  ["current","koer-u2-neubaugasse","Maria Ziegelböck｜U2 Neubaugasse 車站藝術設計","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Neubaugasse"],["交通藝術","建築整合","視覺系統"],"Artistic Design U2 Neubaugasse｜2024","作品把地鐵通行、方向辨識與藝術圖像編成連續的地下經驗，讓車站不只是過境設施，也成為城市公共視覺的一部分。","#{koer}/projects/artistic-design-of-the-u2-station-neubaugasse/","#{koer}/site/assets/files/12490/05maria_ziegelboeck_sketch_24_rendering_abschnitt_1_kleiner.500x0.jpg"],
  ["current","koer-u6-burggasse-passages","Marianne Vlaschits｜U6 Burggasse 通道設計","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Burggasse","Stadthalle"],["交通藝術","壁面藝術","建築整合"],"U6 Burggasse-Stadthalle Passages｜2023","藝術家把兩條地下通道轉成色彩與圖像的穿越場，使原本功能單一的轉乘路徑具有節奏、辨識度與想像性的空間深度。","#{koer}/projects/artistic-design-of-the-passages-of-the-u6-station-burggasse/","#{koer}/site/assets/files/12388/prasentationsposter-1.500x0.jpg"],
  ["current","koer-meidling-passage","Christian Kosmas Mayer｜Meidling 車站通道","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Meidling"],["交通藝術","場域裝置","公共通道"],"Meidling Station Passage｜2023","作品在高頻率的轉乘空間中嵌入歷史與物質線索，讓匆忙移動的人也能從牆面、光線和尺度辨認地方記憶。","#{koer}/projects/artistic-design-of-the-passageway-at-meidling-train-station/","#{koer}/site/assets/files/12058/mayer_1.500x0.jpg"],
  ["current","koer-dimensions-variable-2022","Dimensions Variable｜美泉宮背後的世界","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Schönbrunn","Lainz"],["城市漫遊","檔案研究","地景閱讀"],"Dimensions Variable #｜2022","計畫以漫遊學方法進入美泉宮觀光表象之外的供應、照護與日常地景，使被宏大歷史遮蔽的城市後台成為共同閱讀的檔案。","#{koer}/projects/dimensions-variable-2022/","#{koer}/site/assets/files/11866/abbildung_versorgungsheim_lainz-_foto_alexander_felch.500x0.jpg"],
  ["current","koer-nordbahn-zeh","Leopold Kessler｜Nordbahn-Zeh","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Nordbahnviertel"],["城市介入","公共裝置","基礎設施"],"Nordbahn-Zeh｜2022","一個尺度異常、帶著幽默感的城市物件介入北站新區，藉由日常身體部位與建設環境的錯置，提醒人如何占用並感知新生街區。","#{koer}/projects/nordbahn-zeh/","#{koer}/site/assets/files/11855/nordbahn-zeh_c_leopold_kessler-_2022_3.500x0.jpg"],
  ["current","koer-trash-animal","Bordalo II｜垃圾動物","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["再生材料","生態藝術","大型裝置"],"Trash Animal｜2022","藝術家以廢棄塑膠、金屬與城市殘料組成大型動物，讓污染材料化成直視觀眾的生命形象，將消費廢棄與物種危機放在同一視野。","#{koer}/projects/trash-animal/","#{koer}/site/assets/files/11839/schwarz-5012.500x0.jpg"],
  ["current","koer-femenine","Eva-Maria Schaller、Studio Dan｜FEMENINE","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納"],["表演藝術","聲音藝術","女性主義"],"FEMENINE｜2022","身體、現場音樂與城市空間交織，將女性經驗從被觀看的位置轉成主動生成節奏與關係的公共事件。","#{koer}/projects/femenine/","#{koer}/site/assets/files/11834/femenine_eroeffnung_c_chris_mavric_1-1.500x0.jpg"],
  ["current","koer-living-nonliving-bodies","LIVING AND NON-LIVING BODIES｜公共空間介入","動態情報層","奧地利 / Vienna",["Vienna","Wien","維也納","Operngasse"],["公共介入","跨媒介","身體政治"],"LIVING AND NON-LIVING BODIES｜2022","計畫把牆面、物件、表演者與路人視為共同作用的身體，透過短期介入重新協商 Operngasse 的觀看、停留與權力關係。","#{koer}/projects/operngasse/","#{koer}/site/assets/files/11763/operngasse_wandrelief.500x0.jpg"],
  ["classic-global","koer-weather-tomorrow","KÖR Wien｜明日天氣","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["氣候藝術","公共裝置","城市資訊"],"The Weather of Tomorrow｜2022","作品借用天氣預報的公共語言，讓氣候不只是背景資訊，而成為城市如何想像未來、風險與共同責任的可見介面。","#{koer}/projects/the-weather-of-tomorrow/","#{koer}/site/assets/files/10208/sujet.500x0.jpg"],
  ["classic-global","koer-great-vibration","Moussa Kone｜巨大的震動","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["繪畫裝置","建築介入","公共藝術"],"The Great Vibration｜2022","線條與重複形體在建築尺度上形成視覺震動，讓固定牆面呈現近似聲波與群體能量的動勢。","#{koer}/projects/the-great-vibration/","#{koer}/site/assets/files/10198/62a9914.500x0.jpg"],
  ["classic-global","koer-streamers-covid-sculpture","Benoît Maubrey｜COVID 串流雕塑","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["聲音雕塑","電子媒體","參與式藝術"],"STREAMERS — A COVID Sculpture｜2022","由揚聲器與電子零件構成的雕塑把隔離期間的串流、遠距聲音與公共聚集重新接合，讓技術媒介成為可共同聆聽的城市身體。","#{koer}/projects/streamers-a-covid-sculpture/","#{koer}/site/assets/files/10059/2_streamers.500x0.jpg"],
  ["classic-global","koer-rainbow-hietzing","Markus Tripolt｜給 Hietzing 的彩虹","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納","Hietzing"],["色彩藝術","社區藝術","建築介入"],"A Rainbow for Hietzing｜2021","彩色帶狀形式沿著社區建築展開，以簡單而高辨識度的光譜把教育、聚會與街道視線連成一個共享標記。","#{koer}/projects/a-rainbow-for-hietzing/","#{koer}/site/assets/files/10031/vhs_hietzing_2021_man_9853.500x0.jpg"],
  ["classic-global","koer-themroc","Steinbrener／Dempf & Huber｜Themroc","經典檔案庫","奧地利 / Vienna",["Vienna","Wien","維也納"],["建築介入","城市裝置","觀念藝術"],"Themroc｜2021","作品以帶有電影與反叛文化暗示的建築異常，撕開日常立面秩序，將城市住房、私人領域與公共目光的界線暴露出來。","#{koer}/projects/themroc/","#{koer}/site/assets/files/9964/sdh_themroc_1022410.500x0.jpg"],
  ["classic-german","museum-polis-avramidis","Joannis Avramidis｜Polis","經典檔案庫","德國 / Berlin",["Berlin","柏林","Neue Nationalgalerie","Kulturforum"],["抽象雕塑","建築對話","公共空間"],"Polis｜1970","多個抽象人形量體聚合成緊密群體，置於新國家美術館露台上，作品以身體節奏回應密斯建築的幾何秩序，而非塑造單一英雄。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/polis","https://www.museum-der-1000-orte.de/media/cache/resolve/slider/images/6299e5286787ae1199bb0957ead4ab884470487d.jpg"],
  ["classic-german","museum-multiple-entry","Thomas Florschuetz｜Multiple Entry #6／#21","經典檔案庫","德國 / Berlin",["Berlin","柏林","Bundesministerium für Digitales und Verkehr"],["攝影藝術","建築整合","空間感知"],"Multiple Entry #6／#21｜2001","大型攝影以局部、透視與重複入口介入交通部建築，讓觀看者在真實通道與影像空間之間反覆判讀。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/multiple-entry-6-multiple-entry-21","https://www.museum-der-1000-orte.de/media/cache/resolve/slider/images/1dae1d196619c3e0ea9664ab795a64c64aa19b4b.jpg"],
  ["classic-german","museum-farbgestaltung-golm","Fritz Fuchs｜色彩設計","經典檔案庫","德國 / Potsdam-Golm",["Potsdam","波茨坦","Golm","Max-Planck-Campus"],["色彩系統","建築整合","光環境"],"Farbgestaltung｜1999","半透明與多色的建築色彩系統穿過研究園區立面和室內，使光線、動線與科研工作場景形成持續變化的視覺關係。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/farbgestaltung","https://www.museum-der-1000-orte.de/media/cache/resolve/slider/images/bbeebfb6acb97b7c4f1c2ba8ddd4f03d4e38c4bf.jpg"],
  ["classic-german","museum-spektralsymphonie","Roland Fuhrmann｜元素光譜交響曲","經典檔案庫","德國 / Dresden",["Dresden","德勒斯登","TU Dresden"],["材料藝術","色彩裝置","科學藝術"],"Spektralsymphonie der Elemente｜2010","作品把元素、材料與光譜色彩編成空間序列，讓化學與水研究建築的知識脈絡轉化為可行走、可感知的公共藝術。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/spektralsymphonie-der-elemente","https://www.museum-der-1000-orte.de/media/cache/resolve/slider/images/9bd7ee8cf5b2dbb71f4628060b2999bf4dd385d4.jpg"],
  ["classic-german","museum-aquamobil","Gottfried Gruner｜Aquamobil","經典檔案庫","德國 / Bonn",["Bonn","波昂","Bundesministerium des Innern"],["水景藝術","動力雕塑","環境藝術"],"Aquamobil｜1979","水循環驅動的動態構造在庭院中持續變換，將自然系統、機械節奏與建築氣候連成一個可觀看的微型地景。","https://www.museum-der-1000-orte.de/kunstwerke/kunstwerk/aquamobil","https://www.museum-der-1000-orte.de/media/cache/resolve/slider/images/fa12d20eb08f5266c99f0d7c0df06d3e1d4ab72d.jpg"]
]

arts = art_rows.each_with_index.map do |a, i|
  group,key,title,tier,country,cities,media,work,comment,url,image = a
  number = group == "current" ? i + 1 : group == "classic-global" ? i - 9 : i - 14
  art(id:"#{group}-#{DATE}-#{format('%02d',number)}",key:"art-#{DATE}-#{key}",name:"#{format('%02d',number)}｜#{title}",tier:tier,country:country,cities:cities,media:media,work:work,comment:comment,url:url,image:image)
end

def call(n:, key:, name:, country:, cities:, media:, work:, comment:, url:, image:, deadline:, organizer:, eligibility:, budget:, fee:, timezone:"Europe/Berlin")
  {"category"=>"公開徵件","status"=>"官方來源","updated"=>DATE,"id"=>"competition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"競圖資料庫","region"=>"西方","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>work,"comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>comment,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"deadline"=>deadline,"deadlineLabel"=>work.split("截止 ").last,"deadlineTimezone"=>timezone,"deadlinePrecision"=>"datetime","organizer"=>organizer,"eligibility"=>eligibility,"budget"=>budget,"applicationFee"=>fee,"relatedByCity"=>[]}
end

calls = [
  call(n:1,key:"opportunity-2026-nordart-2027-international-call",name:"Büdelsdorf｜NordArt 2027 國際藝術家徵件",country:"德國 / Büdelsdorf",cities:["Büdelsdorf","比德爾斯多夫","Schleswig-Holstein","Germany","德國"],media:["當代藝術","雕塑公園","裝置藝術"],work:"NordArt 2027 展覽徵件｜截止 2026.10.31 23:59 CET",comment:"歐洲大型年度當代藝術展在舊鑄造廠、歷史廳舍與雕塑公園徵集全球藝術家，作品可在工業建築與戶外地景中建立跨文化對話。",url:"https://www.nordart.de/kuenstlerinnen/bewerbung-2027",image:"https://www.nordart.de/fileadmin/user_upload/NordArt2026_1.jpg",deadline:"2026-10-31T23:59:00+01:00",organizer:"Kunstwerk Carlshütte／NordArt",eligibility:"全球視覺藝術家；可提交最多十件可能展出作品，需現場製作或自行搭建者可申請 Artist in Residence",budget:"入選作品由主辦方展覽保險並負責一般安裝；藝術家自付往返運輸，官方未保證製作費或出席費",fee:"免費"),
  call(n:2,key:"opportunity-2026-stuttgart-hajek100-public-art",name:"Stuttgart｜Hajek100 城市公共藝術徵件",country:"德國 / Stuttgart",cities:["Stuttgart","斯圖加特","Baden-Württemberg","巴登-符騰堡","Germany","德國"],media:["公共藝術","地景藝術","數位介入","參與式藝術"],work:"2027 全城市公共藝術計畫｜截止 2026.10.30 23:59 CET",comment:"徵集雕塑、空間裝置、數位作品、可步行藝術地景、導視系統與參與式計畫，不以傳統紀念形式重述 Hajek，而是把藝術作為城市相遇、定位和公共討論的結構。",url:"https://www.stuttgart.de/service/aktuelle-meldungen/2026/juli/hajek100-stuttgart-sucht-neue-kunst-fuer-den-oeffentlichen-raum",image:"https://www.stuttgart.de/service/aktuelle-meldungen/2026/juli/hajek100-stuttgart-sucht-neue-kunst-fuer-den-oeffentlichen-raum.php.media/487114/Hajekpark-Foto-und-Rechte-Ferdinando-Iannone.jpg.scaled/c07cd2ea9057f1929b285a568544b6b1.jpg",deadline:"2026-10-30T23:59:00+01:00",organizer:"Landeshauptstadt Stuttgart Kulturamt／Otto Herbert Hajek-Kunststiftung",eligibility:"與巴登-符騰堡、尤其斯圖加特地區有關聯的專業藝術家及跨領域團隊",budget:"入選作品可獲實作補助；另設評審獎 €4,000 與觀眾獎 €1,000，個別製作額依官方審定",fee:"免費"),
  call(n:3,key:"opportunity-2026-goethe-international-coproduction-fund-round-2",name:"Munich／全球｜Goethe-Institut 國際共同製作基金",country:"德國 / Munich／International",cities:["Munich","München","慕尼黑","Germany","德國","International","全球"],media:["表演藝術","跨國共製","音樂","舞蹈","劇場"],work:"國際共同製作基金｜截止 2026.10.12 23:59 CET",comment:"德國合作方與境外法律實體共同發展音樂、劇場、舞蹈或跨域表演製作；強調平等協作、跨文化對話與至少一次德國境外的公開呈現。",url:"https://www.goethe.de/en/kul/foe/int.html",image:"https://www.goethe.de/resources/files/jpg1361/tanz_ikf_intro-formatkey-jpg-w320r.jpg",deadline:"2026-10-12T23:59:00+01:00",organizer:"Goethe-Institut e. V.／International Coproduction Fund",eligibility:"申請者須為德國以外（不含奧地利、瑞士）的法律實體，並與德國藝術家、團體或機構建立實質共同製作；領域限音樂、劇場、舞蹈、表演及具表演元素的跨域／數位計畫",budget:"申請金額 €15,000–€30,000，最高補助總製作成本 75%；可列藝術家費、旅費與製作費",fee:"免費"),
  call(n:4,key:"opportunity-2026-ctm-resynthesising-traditional-2027",name:"Berlin｜CTM 2027 Resynthesising the Traditional 藝術研究實驗室",country:"德國 / Berlin",cities:["Berlin","柏林","Germany","德國"],media:["聲音藝術","音樂研究","傳統與科技","藝術實驗室"],work:"藝術研究實驗室｜截止 2026.09.28 23:59 CEST",comment:"面向全球聲音藝術家、音樂人與實踐型研究者，從技術、樂器、作曲、美學或研究方法重新處理傳統與極端聲響之間的張力，並避免把文化遺產固定化或異國情調化。",url:"https://www.ctm-festival.de/festival-2027/open-calls/resynthesising-the-traditional-2027",image:"https://www.ctm-festival.de/fileadmin/_processed_/d/f/csm_bone_flutes_photo_by_HMT_6a8061c9b1.jpg",deadline:"2026-09-28T23:59:00+02:00",organizer:"CTM Festival／Resynthesising the Traditional",eligibility:"全球個人藝術家或實踐型研究者；須已有把傳統聲響／觀念與當代形式連結的實踐，並提出下一階段研究問題；工作語言以英文為主",budget:"每人旅費最高 €300，另含實驗室期間住宿、餐食、CTM 2027 通行證及必要簽證費；後續最多兩件作品可獲 2028 委託機會",fee:"免費"),
  call(n:5,key:"opportunity-2026-zaunergroup-art-award-2027",name:"Bad Schallerbach｜ZAUNERGROUP ART AWARD 2027",country:"奧地利 / Bad Schallerbach",cities:["Bad Schallerbach","巴德沙勒巴赫","Austria","奧地利"],media:["繪畫","版畫","藝術獎"],work:"繪畫與版畫藝術獎｜截止 2026.12.31 23:59 CET",comment:"雙年制藝術獎向在奧地利生活的青年與新銳藝術家徵集繪畫及版畫，入圍作品將於 Galerie Badstrasse 9 進行六週展售。",url:"https://zaunergroup-artaward.at/",image:"https://zaunergroup-artaward.at/wp-content/uploads/2026/08/Zaunergroup-Art-Award.png",deadline:"2026-12-31T23:59:00+01:00",organizer:"ZAUNERGROUP／GALERIE BADSTRASSE 9",eligibility:"45 歲以下、生活重心在奧地利的藝術學生與新銳藝術家；接受繪畫與版畫，每人最多三件作品",budget:"首獎 €20,000；入圍作品於 2027-02-25 頒獎後展出六週",fee:"免費",timezone:"Europe/Vienna")
]

def exhibition(n:, key:, name:, country:, cities:, media:, dates:, url:, image:, type:, edition:, organizer:, curator:, venue:, admission:, comment:, statement:)
  {"category"=>"全球重要展覽","status"=>"官方來源","updated"=>DATE,"id"=>"exhibition-#{DATE}-#{format('%02d',n)}","dedupeKey"=>key,"name"=>"#{format('%02d',n)}｜#{name}","tier"=>"全球重要展覽","region"=>"全球","country"=>country,"cityKeywords"=>cities,"media"=>media,"works"=>"#{type}｜#{dates[0]}–#{dates[1]}","comment"=>comment,"website"=>url,"workPage"=>url,"photo"=>image,"artistStatement"=>statement,"artistStatementSource"=>url,"classicTitle"=>name,"classicImage"=>image,"classicDesc"=>comment,"exhibitionType"=>type,"exhibitionStatus"=>"歷史展覽","startDate"=>dates[0],"endDate"=>dates[1],"edition"=>edition,"organizer"=>organizer,"curator"=>curator,"venue"=>venue,"admission"=>admission,"curatorStatement"=>statement,"curatorStatementSource"=>url,"relatedByCity"=>[]}
end

exhibitions = [
  exhibition(n:1,key:"exhibition-2012-documenta-13-collapse-recovery",name:"documenta 13｜崩解與復原的世界場域",country:"德國 / Kassel",cities:["Kassel","卡塞爾","Kabul","喀布爾","Alexandria","Cairo","Banff"],media:["文件展","國際調查展","跨地域研究"],dates:["2012-06-09","2012-09-16"],url:"https://documenta.de/en/retrospective/documenta-13",image:"https://documenta.de/media/pages/retrospective/documenta-13/5f8e86b0cb-1739818853/d13_plakat_01_335807-1440x.webp",type:"國際當代藝術文件展",edition:"第 13 屆",organizer:"documenta und Museum Fridericianum gGmbH",curator:"Carolyn Christov-Bakargiev（藝術總監）",venue:"卡塞爾，並延伸至喀布爾、亞歷山卓／開羅與班夫",admission:"歷史展覽；當屆售票",comment:"documenta 13 將展覽由卡塞爾延伸至喀布爾、亞歷山卓／開羅和班夫，把藝術作品、研究、檔案與聚會編成多中心的世界場域，回應毀壞、記憶、自然與復原。",statement:"Carolyn Christov-Bakargiev 以『舞台上、撤退中、希望狀態、圍困狀態』等情境取代單一主題，讓 194 位藝術家的工作在不同政治與地理條件間生成關係。"),
  exhibition(n:2,key:"exhibition-2022-singapore-biennale-natasha",name:"新加坡雙年展 2022｜Natasha",country:"新加坡 / Singapore",cities:["Singapore","新加坡","Tanjong Pagar","Lazarus Island","Sentosa"],media:["國際雙年展","群島地景","跨文化研究"],dates:["2022-10-16","2023-03-19"],url:"https://www.singaporeartmuseum.sg/art-events/exhibitions/singapore-biennale-2022",image:"https://www.singaporeartmuseum.sg/-/media/SAM/Images/Singapore-Biennale-2022/SB_Landscape_WebsiteBanner1920x768.jpg?w=1920&hash=F45803E5C873E245194237CB022B10C0",type:"國際當代藝術雙年展",edition:"第 7 屆",organizer:"Singapore Art Museum；受 National Arts Council, Singapore 委託",curator:"Binna Choi、Nida Ghouse、June Yap、Ala Younis（共同藝術總監）",venue:"新加坡藝術博物館及遍布城市與南部島嶼的多處場址",admission:"歷史展覽；部分公共場址免費",comment:"第七屆以人名 Natasha 作為親近而開放的入口，五十多位藝術家和團隊沿著城市、港灣與島嶼展開相遇，讓雙年展成為可被日常生活陪伴的公共存在。",statement:"共同藝術總監以名字取代口號，邀請觀眾透過情感、關係與移動認識藝術；作品不只被安置在展館，也回應新加坡作為島嶼、港口和多元社會的具體條件。"),
  exhibition(n:3,key:"exhibition-2024-apt11-asia-pacific-triennial",name:"第 11 屆亞太當代藝術三年展｜APT11",country:"澳洲 / Brisbane",cities:["Brisbane","布里斯本","Queensland","昆士蘭","QAG","GOMA"],media:["國際三年展","亞太藝術","跨文化策展"],dates:["2024-11-30","2025-04-27"],url:"https://collection.qagoma.qld.gov.au/page/APT11",image:"https://collection.qagoma.qld.gov.au/system/files/styles/wide/private/2025-06/QAG_APT11_installationview_20240930_ccallistemon_022%20%281%29.jpg?itok=pXM6J7Mu",type:"亞太當代藝術三年展",edition:"第 11 屆",organizer:"Queensland Art Gallery｜Gallery of Modern Art（QAGOMA）",curator:"QAGOMA 亞太藝術策展團隊與區域合作夥伴",venue:"Queensland Art Gallery 與 Gallery of Modern Art",admission:"歷史展覽；免費",comment:"APT11 匯集三十多國、七十組藝術家與計畫，從布里斯本建立通往澳洲、亞洲與太平洋當代實踐的入口，並以共同策展深入較少在國際展覽中被看見的文化脈絡。",statement:"展覽由藝術家、策展人、文化盟友與在地夥伴從基層共同塑形；不以單一區域風格概括亞太，而把多種知識、技藝和敘事並置成可持續交流的網絡。"),
  exhibition(n:4,key:"exhibition-2017-skulptur-projekte-muenster",name:"明斯特雕塑計畫 2017｜城市空間十年展",country:"德國 / Münster",cities:["Münster","明斯特","LWL-Museum","Westfalen"],media:["公共藝術十年展","城市介入","行為藝術"],dates:["2017-06-10","2017-10-01"],url:"https://skulptur-projekte-archiv.de/de-de/2017/",image:"https://skulptur-projekte-archiv.de/media/cache/c8/16/c81687f99f74b486bb64d55176d4316b.jpg",type:"國際公共雕塑與城市藝術十年展",edition:"第 5 屆",organizer:"LWL-Museum für Kunst und Kultur／Stadt Münster",curator:"Kasper König（藝術總監）、Britta Peters、Marianne Wagner",venue:"LWL-Museum 與明斯特市中心及周邊公共場址",admission:"免費公共空間展覽",comment:"2017 年計畫把臨時裝置、表演、工作坊與重演帶入城市，不以雕塑占據場所，而讓作品啟動歷史、建築、社會和政治關係。",statement:"策展聚焦身體的出現與消失、時間性和共同生產，透過 Out of Body、Out of Time、Out of Place 等框架擴張公共雕塑的定義。"),
  exhibition(n:5,key:"exhibition-2022-okayama-art-summit-dream-same-sky",name:"岡山藝術交流 2022｜我們是否夢在同一片天空下",country:"日本 / Okayama",cities:["Okayama","岡山","Okayama Castle","岡山城","Korakuen","後樂園"],media:["國際三年展","城市地景","當代藝術"],dates:["2022-09-30","2022-11-27"],url:"https://www.okayamaartsummit.jp/2022/en/about/",image:"https://www.okayamaartsummit.jp/2022/wp/wp-content/uploads/2022/11/OK4-scaled.jpg",type:"國際當代藝術三年展",edition:"第 3 屆",organizer:"Okayama Art Summit Executive Committee（Okayama City、Ishikawa Foundation、Okayama Prefecture）",curator:"Rirkrit Tiravanija（藝術總監）",venue:"岡山城與岡山後樂園周邊十處歷史、文化及公共場址",admission:"歷史展覽；當屆售票，部分公共場址免費",comment:"展覽把二十八組藝術家帶入岡山城、後樂園、舊校舍、神社、公園與文化設施，使當代藝術沿著城市歷史地景形成可步行的三年展網絡。",statement:"Rirkrit Tiravanija 以沒有問號的『Do we dream under the same sky』打開差異與多重敘事：夢不是要求一致，而是讓位於西方中心之外的生活史、移動背景和觀看方式彼此相遇。")
]

def related(item, candidates)
  keys=item.fetch("cityKeywords",[]).map{|x|x.downcase.strip}
  candidates.select{|o|!(keys & o.fetch("cityKeywords",[]).map{|x|x.downcase.strip}).empty?}.map{|o|o["id"]}.uniq
end

comp_path=File.join(DATA,"competitions.json"); comp=JSON.parse(File.read(comp_path))
expired_path=File.join(DATA,"expired-20260913.json")
previous_expired=Dir[File.join(DATA,"expired-*.json")].reject{|p|p==expired_path}.flat_map{|p|JSON.parse(File.read(p)).fetch("entries",[])}
existing_expired=File.exist?(expired_path) ? JSON.parse(File.read(expired_path)).fetch("entries",[]) : []
today_expired=comp["entries"].select{|e|e["deadline"] && DateTime.parse(e["deadline"])<=NOW}
archive=(previous_expired+existing_expired+today_expired).uniq{|e|e["dedupeKey"]||e["id"]}
old_keys=previous_expired.map{|e|e["dedupeKey"]||e["id"]}.uniq
removed=archive.count{|e|!old_keys.include?(e["dedupeKey"]||e["id"])}
comp["entries"].reject!{|e|today_expired.include?(e)||e["updated"]==DATE}
existing_keys=comp["entries"].map{|e|e["dedupeKey"]}; calls.each{|e|comp["entries"]<<e unless existing_keys.include?(e["dedupeKey"])}

all_art_files=Dir[File.join(DATA,"backfill-{july,august,september}-*.json")].reject{|p|p.end_with?("manifest.json")||p.end_with?("20260913.json")}
all_art=all_art_files.flat_map{|p|v=JSON.parse(File.read(p));v.is_a?(Hash)?v.fetch("entries",[]):v}+arts
arts.each{|e|e["relatedByCity"]=related(e,comp["entries"])}
comp["entries"].each{|e|e["relatedByCity"]=related(e,all_art)}

daily={"meta"=>{"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"total"=>20,"dynamicEntries"=>10,"globalClassicEntries"=>5,"germanClassicEntries"=>5,"source"=>"KÖR Wien、Museum der 1000 Orte 官方頁","selectionPolicy"=>"優先地景、生態、參與、聲光、動態、數位與建築整合作品；不以傳統人物、胸像、騎馬像或基座式紀念碑湊數。","note"=>"9/13 週更固定 10＋5＋5；另有有效公開徵選 5 則與全球重要展覽 5 篇。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"checkedUniqueSources"=>20,"brokenOrBlockedReplaced"=>0,"rule"=>"實際瀏覽器逐頁開啟"},"imageAudit"=>{"checkedAt"=>GENERATED_AT,"imageEntries"=>20,"missing"=>0,"rule"=>"官方圖片逐一載入驗證"}},"entries"=>arts}
comp["meta"]={"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"weeklyTarget"=>5,"source"=>"官方主辦機構徵件頁","activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>4,"expiredRemoved"=>removed,"note"=>"9/13 新增 5 筆有效公開徵選，其中 4 筆德國案件；移除 #{removed} 筆逾期案件。","linkAudit"=>{"checkedAt"=>GENERATED_AT,"missingCityKeywords"=>0,"uniqueNewSourcesChecked"=>5,"blockedSourceReplaced"=>2}}

ex_path=File.join(DATA,"exhibitions.json"); ex=JSON.parse(File.read(ex_path)); ex["entries"].reject!{|e|e["updated"]==DATE}
ex_keys=ex["entries"].map{|e|e["dedupeKey"]}; exhibitions.each{|e|ex["entries"]<<e unless ex_keys.include?(e["dedupeKey"])}
ex["meta"]={"generatedAt"=>GENERATED_AT,"timezone"=>"Asia/Taipei","date"=>DATE,"weeklyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"9/13 新增 5 篇全球重要展覽；全部使用官方來源與可載入圖片。"}

File.write(File.join(DATA,"backfill-september-20260913.json"),JSON.pretty_generate(daily)+"\n")
File.write(comp_path,JSON.pretty_generate(comp)+"\n");File.write(ex_path,JSON.pretty_generate(ex)+"\n")
sept_path=File.join(DATA,"backfill-september-manifest.json");sept=JSON.parse(File.read(sept_path));files=(sept.fetch("files",[])+["backfill-september-20260913.json"]).uniq.sort
sept.merge!({"version"=>"2026-09-13-public-art-r65","generatedAt"=>GENERATED_AT,"files"=>files,"expectedEntries"=>files.length*20,"statementEntries"=>files.length*20,"statementSourceEntries"=>files.length*20,"statementBacklog"=>0,"imageEntries"=>files.length*20,"imageBacklog"=>0,"note"=>"截至 2026-09-13 累計 #{files.length*20} 則；本週新增 20 則公共藝術（10／5／5），已套用非傳統紀念碑選材規則。"});File.write(sept_path,JSON.pretty_generate(sept)+"\n")
cm_path=File.join(DATA,"competition-manifest.json");cm=JSON.parse(File.read(cm_path));cm.merge!({"version"=>"2026-09-13-competition-r41","generatedAt"=>GENERATED_AT,"activeEntries"=>comp["entries"].length,"addedToday"=>5,"germanAddedToday"=>4,"expiredRemoved"=>removed,"deadlineTimezoneEntries"=>comp["entries"].count{|e|e["deadlineTimezone"]},"deadlinePrecisionEntries"=>comp["entries"].count{|e|e["deadlinePrecision"]},"cityKeywordEntries"=>comp["entries"].count{|e|!e.fetch("cityKeywords",[]).empty?},"note"=>"2026-09-13 新增 5 則有效公開徵選（德國 4）並移除 #{removed} 則逾期案件。"});File.write(cm_path,JSON.pretty_generate(cm)+"\n")
em_path=File.join(DATA,"exhibition-manifest.json");em=JSON.parse(File.read(em_path));em.merge!({"version"=>"2026-09-13-global-exhibitions-r11","generatedAt"=>GENERATED_AT,"weeklyTarget"=>5,"totalEntries"=>ex["entries"].length,"addedToday"=>5,"officialSourceEntries"=>ex["entries"].count{|e|e["status"]=="官方來源"},"imageEntries"=>ex["entries"].count{|e|!e["photo"].to_s.empty?},"note"=>"2026-09-13 新增 5 篇全球重要展覽；全部使用官方來源與可顯示圖片。"});File.write(em_path,JSON.pretty_generate(em)+"\n")
File.write(expired_path,JSON.pretty_generate({"archivedAt"=>GENERATED_AT,"removedToday"=>removed,"entries"=>archive})+"\n")
index_path=File.join(ROOT,"index.html");index=File.read(index_path).gsub("20260908-daily-r64","20260913-weekly-r65");File.write(index_path,index)
File.write(File.join(DATA,"deploy-touch.txt"),"2026-09-13 weekly r65 — 20 public artworks + 5 active open calls (4 Germany) + 5 global exhibitions; #{removed} expired calls removed.\n")
puts JSON.pretty_generate({date:DATE,public_art:arts.length,dynamic:10,global_classics:5,german_classics:5,calls:calls.length,exhibitions:exhibitions.length,expired_removed:removed})
